In [1]:
import pandas as pd

# Series
# A Series is a one-dimensional labeled array capable of holding any data type (integers, strings, floating point numbers, Python objects, etc.). 
# The axis labels are collectively referred to as the index. A Series is like a fixed-size dictionary in that you can get and set values by index label.

pd.Series(data=["Chocolate", "Vanilla", "Strawberry","Rum Raisin"])

0     Chocolate
1       Vanilla
2    Strawberry
3    Rum Raisin
dtype: str

In [2]:
pd.Series(data=[1, 2, 3, 4])

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
registration = [True, False, True, False]
pd.Series(data=registration)

0     True
1    False
2     True
3    False
dtype: bool

In [4]:
# Create a Series from a Dictionary
# Keys are used as index labels and values are used as the data for the Series. The values in the Series will be in the same order as the keys in the dictionary.
sushi = {
    "Salmon": "Orange",
    "Tuna": "Red",
    "Eel" : "Brown"
}
pd.Series(data=sushi)

Salmon    Orange
Tuna         Red
Eel        Brown
dtype: str

In [5]:
prices = pd.Series([2.99,4.45,3.46])
prices

0    2.99
1    4.45
2    3.46
dtype: float64

In [6]:
# Series methods
prices.sum()

np.float64(10.9)

In [7]:
prices.product()

np.float64(46.03703000000001)

In [8]:
prices.mean()

np.float64(3.6333333333333333)

In [9]:
prices.std()

np.float64(0.7452739988308551)

In [10]:
# Series Attributes
adjectives = pd.Series(["Smart","Handsome","Charming","Brilliant","Humble","Smart"])

In [11]:
adjectives.size

6

In [12]:
adjectives.is_unique

False

In [13]:
# composition is made up of values and index
adjectives.values

<StringArray>
['Smart', 'Handsome', 'Charming', 'Brilliant', 'Humble', 'Smart']
Length: 6, dtype: str

In [14]:
adjectives.index

RangeIndex(start=0, stop=6, step=1)

In [15]:
type(adjectives.values)

pandas.arrays.StringArray

In [16]:
type(adjectives.index)

pandas.RangeIndex

In [17]:
# a parameters is the name of the input, an argument is the actual value passed to the function.

fruits = ["Apple", "Banana", "Cherry","Orange","Plum","Durian"]
weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday","Monday"]
pd.Series(fruits, weekdays)

Monday        Apple
Tuesday      Banana
Wednesday    Cherry
Thursday     Orange
Friday         Plum
Monday       Durian
dtype: str

In [18]:
pd.Series(weekdays, fruits)

Apple        Monday
Banana      Tuesday
Cherry    Wednesday
Orange     Thursday
Plum         Friday
Durian       Monday
dtype: str

In [19]:
pd.Series(data=fruits, index=weekdays)

Monday        Apple
Tuesday      Banana
Wednesday    Cherry
Thursday     Orange
Friday         Plum
Monday       Durian
dtype: str

In [20]:
pd.Series(index=weekdays, data=fruits)

Monday        Apple
Tuesday      Banana
Wednesday    Cherry
Thursday     Orange
Friday         Plum
Monday       Durian
dtype: str

In [21]:
pd.Series(fruits, index=weekdays)

Monday        Apple
Tuesday      Banana
Wednesday    Cherry
Thursday     Orange
Friday         Plum
Monday       Durian
dtype: str

In [22]:
fruits_series = pd.Series(fruits, index=weekdays)
fruits_series.ndim

1

In [23]:
fruits_df = pd.DataFrame(fruits_series)
fruits_df.ndim

2

In [24]:
fruits_df.index

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday'], dtype='str')

In [25]:
fruits_df.loc['Monday']

             0
Monday   Apple
Monday  Durian

In [26]:
fruits_df.iloc[0]

0    Apple
Name: Monday, dtype: str

In [27]:
fruits_df.index

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday'], dtype='str')

In [28]:
fruits_series.index

Index(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday'], dtype='str')

In [29]:
fruits_df.loc['Monday']

             0
Monday   Apple
Monday  Durian

In [30]:
pokemon = pd.read_csv("data/pokemon.csv", usecols=["Name"]).squeeze("columns")
google  = pd.read_csv("data/google_stock_price.csv", usecols=["Price"]).squeeze("columns")

In [31]:
type(google)

pandas.Series

In [32]:
len(google)

4793

In [33]:
list(pokemon)

['Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran♀',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 'Farfetch’d',
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew',
 'Chikorita',
 'Bayleef',
 'Meganium',
 'Cyndaquil',
 'Quilava',
 'Typhlosion',
 'Totodile',
 'Croconaw',
 'Feraligatr',
 'Sentret',
 'Furret',
 'Hoothoot',
 'Noctowl',
 'Ledyba',
 'Ledian',
 'Spinarak',
 'Ariados',
 'Crobat',
 'Chinchou',
 'Lanturn',
 'Pichu',
 'Cleffa',
 'Igglybuff',
 'Togepi',
 'Togetic',
 'Natu',
 'Xatu',
 'Mareep',
 'Flaaffy',
 'Ampharos',
 'Bellossom',
 'Marill',
 'Azumarill',
 'Sudowoodo',
 'Politoed',
 'Hoppip',
 'Skiploom',
 'Jumpluff',
 'Aipom',
 'Sunkern',
 'Sunflora',
 'Yanma',
 'Wooper',
 'Quagsire',
 'Espeon',
 'Umbreon',
 'Murkrow',
 'Slowking',
 'Misdreavus',
 'Unown',
 'Wobbuffet',
 'Girafarig',
 'Pineco',
 'Forretress',
 'Dunsparce',
 'Gligar',
 'Steelix',
 'Snubbull',
 'Granbull',
 'Qwilfish',
 'Scizor',
 'Shuckle',
 'Heracross',
 'Sneasel',
 'Teddiursa',
 'Ursaring',
 'Slugma',
 'Magcargo',
 'Swinub',
 'Piloswine',
 'Corsola',
 'Remoraid',
 'Octillery',
 'Delibird',
 'Mantine',
 'Skarmory',
 'Houndour',
 'Houndoom',
 'Kingdra',
 'Phanpy',
 'Donphan',
 'Porygon2',
 'Stantler',
 'Smeargle',
 'Tyrogue',
 'Hitmontop',
 'Smoochum',
 'Elekid',
 'Magby',
 'Miltank',
 'Blissey',
 'Raikou',
 'Entei',
 'Suicune',
 'Larvitar',
 'Pupitar',
 'Tyranitar',
 'Lugia',
 'Ho-Oh',
 'Celebi',
 'Treecko',
 'Grovyle',
 'Sceptile',
 'Torchic',
 'Combusken',
 'Blaziken',
 'Mudkip',
 'Marshtomp',
 'Swampert',
 'Poochyena',
 'Mightyena',
 'Zigzagoon',
 'Linoone',
 'Wurmple',
 'Silcoon',
 'Beautifly',
 'Cascoon',
 'Dustox',
 'Lotad',
 'Lombre',
 'Ludicolo',
 'Seedot',
 'Nuzleaf',
 'Shiftry',
 'Taillow',
 'Swellow',
 'Wingull',
 'Pelipper',
 'Ralts',
 'Kirlia',
 'Gardevoir',
 'Surskit',
 'Masquerain',
 'Shroomish',
 'Breloom',
 'Slakoth',
 'Vigoroth',
 'Slaking',
 'Nincada',
 'Ninjask',
 'Shedinja',
 'Whismur',
 'Loudred',
 'Exploud',
 'Makuhita',
 'Hariyama',
 'Azurill',
 'Nosepass',
 'Skitty',
 'Delcatty',
 'Sableye',
 'Mawile',
 'Aron',
 'Lairon',
 'Aggron',
 'Meditite',
 'Medicham',
 'Electrike',
 'Manectric',
 'Plusle',
 'Minun',
 'Volbeat',
 'Illumise',
 'Roselia',
 'Gulpin',
 'Swalot',
 'Carvanha',
 'Sharpedo',
 'Wailmer',
 'Wailord',
 'Numel',
 'Camerupt',
 'Torkoal',
 'Spoink',
 'Grumpig',
 'Spinda',
 'Trapinch',
 'Vibrava',
 'Flygon',
 'Cacnea',
 'Cacturne',
 'Swablu',
 'Altaria',
 'Zangoose',
 'Seviper',
 'Lunatone',
 'Solrock',
 'Barboach',
 'Whiscash',
 'Corphish',
 'Crawdaunt',
 'Baltoy',
 'Claydol',
 'Lileep',
 'Cradily',
 'Anorith',
 'Armaldo',
 'Feebas',
 'Milotic',
 'Castform',
 'Kecleon',
 'Shuppet',
 'Banette',
 'Duskull',
 'Dusclops',
 'Tropius',
 'Chimecho',
 'Absol',
 'Wynaut',
 'Snorunt',
 'Glalie',
 'Spheal',
 'Sealeo',
 'Walrein',
 'Clamperl',
 'Huntail',
 'Gorebyss',
 'Relicanth',
 'Luvdisc',
 'Bagon',
 'Shelgon',
 'Salamence',
 'Beldum',
 'Metang',
 'Metagross',
 'Regirock',
 'Regice',
 'Registeel',
 'Latias',
 'Latios',
 'Kyogre',
 'Groudon',
 'Rayquaza',
 'Jirachi',
 'Deoxys',
 'Turtwig',
 'Grotle',
 'Torterra',
 'Chimchar',
 'Monferno',
 'Infernape',
 'Piplup',
 'Prinplup',
 'Empoleon',
 'Starly',
 'Staravia',
 'Staraptor',
 'Bidoof',
 'Bibarel',
 'Kricketot',
 'Kricketune',
 'Shinx',
 'Luxio',
 'Luxray',
 'Budew',
 'Roserade',
 'Cranidos',
 'Rampardos',
 'Shieldon',
 'Bastiodon',
 'Burmy',
 'Wormadam',
 'Mothim',
 'Combee',
 'Vespiquen',
 'Pachirisu',
 'Buizel',
 'Floatzel',
 'Cherubi',
 'Cherrim',
 'Shellos',
 'Gastrodon',
 'Ambipom',
 'Drifloon',
 'Drifblim',
 'Buneary',
 'Lopunny',
 'Mismagius',
 'Honchkrow',
 'Glameow',
 'Purugly',
 'Chingling',
 'Stunky',
 'Skuntank',
 'Bronzor',
 'Bronzong',
 'Bonsly',
 'Mime Jr.',
 'Happiny',
 'Chatot',
 'Spiritomb',
 'Gible',
 'Gabite',
 'Garchomp',
 'Munchlax',
 'Riolu',
 'Lucario',
 'Hippopotas',
 'Hippowdon',
 'Skorupi',
 'Drapion',
 'Croagunk',
 'Toxicroak',
 'Carnivine',
 'Finneon',
 'Lumineon',
 'Mantyke',
 'Snover',
 'Abomasnow',
 'Weavile',
 'Magnezone',
 'Lickilicky',
 'Rhyperior',
 'Tangrowth',
 'Electivire',
 'Magmortar',
 'Togekiss',
 'Yanmega',
 'Leafeon',
 'Glaceon',
 'Gliscor',
 'Mamoswine',
 'Porygon-Z',
 'Gallade',
 'Probopass',
 'Dusknoir',
 'Froslass',
 'Rotom',
 'Uxie',
 'Mesprit',
 'Azelf',
 'Dialga',
 'Palkia',
 'Heatran',
 'Regigigas',
 'Giratina',
 'Cresselia',
 'Phione',
 'Manaphy',
 'Darkrai',
 'Shaymin',
 'Arceus',
 'Victini',
 'Snivy',
 'Servine',
 'Serperior',
 'Tepig',
 'Pignite',
 'Emboar',
 'Oshawott',
 'Dewott',
 'Samurott',
 'Patrat',
 'Watchog',
 'Lillipup',
 'Herdier',
 'Stoutland',
 'Purrloin',
 'Liepard',
 'Pansage',
 'Simisage',
 'Pansear',
 'Simisear',
 'Panpour',
 'Simipour',
 'Munna',
 'Musharna',
 'Pidove',
 'Tranquill',
 'Unfezant',
 'Blitzle',
 'Zebstrika',
 'Roggenrola',
 'Boldore',
 'Gigalith',
 'Woobat',
 'Swoobat',
 'Drilbur',
 'Excadrill',
 'Audino',
 'Timburr',
 'Gurdurr',
 'Conkeldurr',
 'Tympole',
 'Palpitoad',
 'Seismitoad',
 'Throh',
 'Sawk',
 'Sewaddle',
 'Swadloon',
 'Leavanny',
 'Venipede',
 'Whirlipede',
 'Scolipede',
 'Cottonee',
 'Whimsicott',
 'Petilil',
 'Lilligant',
 'Basculin',
 'Sandile',
 'Krokorok',
 'Krookodile',
 'Darumaka',
 'Darmanitan',
 'Maractus',
 'Dwebble',
 'Crustle',
 'Scraggy',
 'Scrafty',
 'Sigilyph',
 'Yamask',
 'Cofagrigus',
 'Tirtouga',
 'Carracosta',
 'Archen',
 'Archeops',
 'Trubbish',
 'Garbodor',
 'Zorua',
 'Zoroark',
 'Minccino',
 'Cinccino',
 'Gothita',
 'Gothorita',
 'Gothitelle',
 'Solosis',
 'Duosion',
 'Reuniclus',
 'Ducklett',
 'Swanna',
 'Vanillite',
 'Vanillish',
 'Vanilluxe',
 'Deerling',
 'Sawsbuck',
 'Emolga',
 'Karrablast',
 'Escavalier',
 'Foongus',
 'Amoonguss',
 'Frillish',
 'Jellicent',
 'Alomomola',
 'Joltik',
 'Galvantula',
 'Ferroseed',
 'Ferrothorn',
 'Klink',
 'Klang',
 'Klinklang',
 'Tynamo',
 'Eelektrik',
 'Eelektross',
 'Elgyem',
 'Beheeyem',
 'Litwick',
 'Lampent',
 'Chandelure',
 'Axew',
 'Fraxure',
 'Haxorus',
 'Cubchoo',
 'Beartic',
 'Cryogonal',
 'Shelmet',
 'Accelgor',
 'Stunfisk',
 'Mienfoo',
 'Mienshao',
 'Druddigon',
 'Golett',
 'Golurk',
 'Pawniard',
 'Bisharp',
 'Bouffalant',
 'Rufflet',
 'Braviary',
 'Vullaby',
 'Mandibuzz',
 'Heatmor',
 'Durant',
 'Deino',
 'Zweilous',
 'Hydreigon',
 'Larvesta',
 'Volcarona',
 'Cobalion',
 'Terrakion',
 'Virizion',
 'Tornadus',
 'Thundurus',
 'Reshiram',
 'Zekrom',
 'Landorus',
 'Kyurem',
 'Keldeo',
 'Meloetta',
 'Genesect',
 'Chespin',
 'Quilladin',
 'Chesnaught',
 'Fennekin',
 'Braixen',
 'Delphox',
 'Froakie',
 'Frogadier',
 'Greninja',
 'Bunnelby',
 'Diggersby',
 'Fletchling',
 'Fletchinder',
 'Talonflame',
 'Scatterbug',
 'Spewpa',
 'Vivillon',
 'Litleo',
 'Pyroar',
 'Flabébé',
 'Floette',
 'Florges',
 'Skiddo',
 'Gogoat',
 'Pancham',
 'Pangoro',
 'Furfrou',
 'Espurr',
 'Meowstic',
 'Honedge',
 'Doublade',
 'Aegislash',
 'Spritzee',
 'Aromatisse',
 'Swirlix',
 'Slurpuff',
 'Inkay',
 'Malamar',
 'Binacle',
 'Barbaracle',
 'Skrelp',
 'Dragalge',
 'Clauncher',
 'Clawitzer',
 'Helioptile',
 'Heliolisk',
 'Tyrunt',
 'Tyrantrum',
 'Amaura',
 'Aurorus',
 'Sylveon',
 'Hawlucha',
 'Dedenne',
 'Carbink',
 'Goomy',
 'Sliggoo',
 'Goodra',
 'Klefki',
 'Phantump',
 'Trevenant',
 'Pumpkaboo',
 'Gourgeist',
 'Bergmite',
 'Avalugg',
 'Noibat',
 'Noivern',
 'Xerneas',
 'Yveltal',
 'Zygarde',
 'Diancie',
 'Hoopa',
 'Volcanion',
 'Rowlet',
 'Dartrix',
 'Decidueye',
 'Litten',
 'Torracat',
 'Incineroar',
 'Popplio',
 'Brionne',
 'Primarina',
 'Pikipek',
 'Trumbeak',
 'Toucannon',
 'Yungoos',
 'Gumshoos',
 'Grubbin',
 'Charjabug',
 'Vikavolt',
 'Crabrawler',
 'Crabominable',
 'Oricorio',
 'Cutiefly',
 'Ribombee',
 'Rockruff',
 'Lycanroc',
 'Wishiwashi',
 'Mareanie',
 'Toxapex',
 'Mudbray',
 'Mudsdale',
 'Dewpider',
 'Araquanid',
 'Fomantis',
 'Lurantis',
 'Morelull',
 'Shiinotic',
 'Salandit',
 'Salazzle',
 'Stufful',
 'Bewear',
 'Bounsweet',
 'Steenee',
 'Tsareena',
 'Comfey',
 'Oranguru',
 'Passimian',
 'Wimpod',
 'Golisopod',
 'Sandygast',
 'Palossand',
 'Pyukumuku',
 'Type: Null',
 'Silvally',
 'Minior',
 'Komala',
 'Turtonator',
 'Togedemaru',
 'Mimikyu',
 'Bruxish',
 'Drampa',
 'Dhelmise',
 'Jangmo-o',
 'Hakamo-o',
 'Kommo-o',
 'Tapu Koko',
 'Tapu Lele',
 'Tapu Bulu',
 'Tapu Fini',
 'Cosmog',
 'Cosmoem',
 'Solgaleo',
 'Lunala',
 'Nihilego',
 'Buzzwole',
 'Pheromosa',
 'Xurkitree',
 'Celesteela',
 'Kartana',
 'Guzzlord',
 'Necrozma',
 'Magearna',
 'Marshadow',
 'Poipole',
 'Naganadel',
 'Stakataka',
 'Blacephalon',
 'Zeraora',
 'Meltan',
 'Melmetal',
 'Grookey',
 'Thwackey',
 'Rillaboom',
 'Scorbunny',
 'Raboot',
 'Cinderace',
 'Sobble',
 'Drizzile',
 'Inteleon',
 'Skwovet',
 'Greedent',
 'Rookidee',
 'Corvisquire',
 'Corviknight',
 'Blipbug',
 'Dottler',
 'Orbeetle',
 'Nickit',
 'Thievul',
 'Gossifleur',
 'Eldegoss',
 'Wooloo',
 'Dubwool',
 'Chewtle',
 'Drednaw',
 'Yamper',
 'Boltund',
 'Rolycoly',
 'Carkol',
 'Coalossal',
 'Applin',
 'Flapple',
 'Appletun',
 'Silicobra',
 'Sandaconda',
 'Cramorant',
 'Arrokuda',
 'Barraskewda',
 'Toxel',
 'Toxtricity',
 'Sizzlipede',
 'Centiskorch',
 'Clobbopus',
 'Grapploct',
 'Sinistea',
 'Polteageist',
 'Hatenna',
 'Hattrem',
 'Hatterene',
 'Impidimp',
 'Morgrem',
 'Grimmsnarl',
 'Obstagoon',
 'Perrserker',
 'Cursola',
 'Sirfetch’d',
 'Mr. Rime',
 'Runerigus',
 'Milcery',
 'Alcremie',
 'Falinks',
 'Pincurchin',
 'Snom',
 'Frosmoth',
 'Stonjourner',
 'Eiscue',
 'Indeedee',
 'Morpeko',
 'Cufant',
 'Copperajah',
 'Dracozolt',
 'Arctozolt',
 'Dracovish',
 'Arctovish',
 'Duraludon',
 'Dreepy',
 'Drakloak',
 'Dragapult',
 'Zacian',
 'Zamazenta',
 'Eternatus',
 'Kubfu',
 'Urshifu',
 'Zarude',
 'Regieleki',
 'Regidrago',
 'Glastrier',
 'Spectrier',
 'Calyrex',
 'Wyrdeer',
 'Kleavor',
 'Ursaluna',
 'Basculegion',
 'Sneasler',
 'Overqwil',
 'Enamorus',
 'Sprigatito',
 'Floragato',
 'Meowscarada',
 'Fuecoco',
 'Crocalor',
 'Skeledirge',
 'Quaxly',
 'Quaxwell',
 'Quaquaval',
 'Lechonk',
 'Oinkologne',
 'Tarountula',
 'Spidops',
 'Nymble',
 'Lokix',
 'Pawmi',
 'Pawmo',
 'Pawmot',
 'Tandemaus',
 'Maushold',
 'Fidough',
 'Dachsbun',
 'Smoliv',
 'Dolliv',
 'Arboliva',
 'Squawkabilly',
 'Nacli',
 'Naclstack',
 'Garganacl',
 'Charcadet',
 'Armarouge',
 'Ceruledge',
 'Tadbulb',
 'Bellibolt',
 'Wattrel',
 'Kilowattrel',
 'Maschiff',
 'Mabosstiff',
 'Shroodle',
 'Grafaiai',
 'Bramblin',
 'Brambleghast',
 'Toedscool',
 'Toedscruel',
 'Klawf',
 'Capsakid',
 'Scovillain',
 'Rellor',
 'Rabsca',
 'Flittle',
 'Espathra',
 'Tinkatink',
 'Tinkatuff',
 'Tinkaton',
 'Wiglett',
 'Wugtrio',
 'Bombirdier',
 'Finizen',
 'Palafin',
 'Varoom',
 'Revavroom',
 'Cyclizar',
 'Orthworm',
 'Glimmet',
 'Glimmora',
 'Greavard',
 'Houndstone',
 'Flamigo',
 'Cetoddle',
 'Cetitan',
 'Veluza',
 'Dondozo',
 'Tatsugiri',
 'Annihilape',
 'Clodsire',
 'Farigiraf',
 'Dudunsparce',
 'Kingambit',
 'Great Tusk',
 'Scream Tail',
 'Brute Bonnet',
 'Flutter Mane',
 'Slither Wing',
 'Sandy Shocks',
 'Iron Treads',
 'Iron Bundle',
 'Iron Hands',
 'Iron Jugulis',
 'Iron Moth',
 'Iron Thorns',
 'Frigibax',
 'Arctibax',
 'Baxcalibur',
 'Gimmighoul',
 'Gholdengo',
 ...]

In [34]:
sorted(pokemon)

['Abomasnow',
 'Abra',
 'Absol',
 'Accelgor',
 'Aegislash',
 'Aerodactyl',
 'Aggron',
 'Aipom',
 'Alakazam',
 'Alcremie',
 'Alomomola',
 'Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'Annihilape',
 'Anorith',
 'Appletun',
 'Applin',
 'Araquanid',
 'Arbok',
 'Arboliva',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Arctibax',
 'Arctovish',
 'Arctozolt',
 'Ariados',
 'Armaldo',
 'Armarouge',
 'Aromatisse',
 'Aron',
 'Arrokuda',
 'Articuno',
 'Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'Barbaracle',
 'Barboach',
 'Barraskewda',
 'Basculegion',
 'Basculin',
 'Bastiodon',
 'Baxcalibur',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellibolt',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bewear',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blacephalon',
 'Blastoise',
 'Blaziken',
 'Blipbug',
 'Blissey',
 'Blitzle',
 'Boldore',
 'Boltund',
 'Bombirdier',
 'Bonsly',
 'Bouffalant',
 'Bounsweet',
 'Braixen',
 'Brambleghast',
 'Bramblin',
 'Braviary',
 'Breloom',
 'Brionne',
 'Bronzong',
 'Bronzor',
 'Brute Bonnet',
 'Bruxish',
 'Budew',
 'Buizel',
 'Bulbasaur',
 'Buneary',
 'Bunnelby',
 'Burmy',
 'Butterfree',
 'Buzzwole',
 'Cacnea',
 'Cacturne',
 'Calyrex',
 'Camerupt',
 'Capsakid',
 'Carbink',
 'Carkol',
 'Carnivine',
 'Carracosta',
 'Carvanha',
 'Cascoon',
 'Castform',
 'Caterpie',
 'Celebi',
 'Celesteela',
 'Centiskorch',
 'Ceruledge',
 'Cetitan',
 'Cetoddle',
 'Chandelure',
 'Chansey',
 'Charcadet',
 'Charizard',
 'Charjabug',
 'Charmander',
 'Charmeleon',
 'Chatot',
 'Cherrim',
 'Cherubi',
 'Chesnaught',
 'Chespin',
 'Chewtle',
 'Chi-Yu',
 'Chien-Pao',
 'Chikorita',
 'Chimchar',
 'Chimecho',
 'Chinchou',
 'Chingling',
 'Cinccino',
 'Cinderace',
 'Clamperl',
 'Clauncher',
 'Clawitzer',
 'Claydol',
 'Clefable',
 'Clefairy',
 'Cleffa',
 'Clobbopus',
 'Clodsire',
 'Cloyster',
 'Coalossal',
 'Cobalion',
 'Cofagrigus',
 'Combee',
 'Combusken',
 'Comfey',
 'Conkeldurr',
 'Copperajah',
 'Corphish',
 'Corsola',
 'Corviknight',
 'Corvisquire',
 'Cosmoem',
 'Cosmog',
 'Cottonee',
 'Crabominable',
 'Crabrawler',
 'Cradily',
 'Cramorant',
 'Cranidos',
 'Crawdaunt',
 'Cresselia',
 'Croagunk',
 'Crobat',
 'Crocalor',
 'Croconaw',
 'Crustle',
 'Cryogonal',
 'Cubchoo',
 'Cubone',
 'Cufant',
 'Cursola',
 'Cutiefly',
 'Cyclizar',
 'Cyndaquil',
 'Dachsbun',
 'Darkrai',
 'Darmanitan',
 'Dartrix',
 'Darumaka',
 'Decidueye',
 'Dedenne',
 'Deerling',
 'Deino',
 'Delcatty',
 'Delibird',
 'Delphox',
 'Deoxys',
 'Dewgong',
 'Dewott',
 'Dewpider',
 'Dhelmise',
 'Dialga',
 'Diancie',
 'Diggersby',
 'Diglett',
 'Ditto',
 'Dodrio',
 'Doduo',
 'Dolliv',
 'Dondozo',
 'Donphan',
 'Dottler',
 'Doublade',
 'Dracovish',
 'Dracozolt',
 'Dragalge',
 'Dragapult',
 'Dragonair',
 'Dragonite',
 'Drakloak',
 'Drampa',
 'Drapion',
 'Dratini',
 'Drednaw',
 'Dreepy',
 'Drifblim',
 'Drifloon',
 'Drilbur',
 'Drizzile',
 'Drowzee',
 'Druddigon',
 'Dubwool',
 'Ducklett',
 'Dudunsparce',
 'Dugtrio',
 'Dunsparce',
 'Duosion',
 'Duraludon',
 'Durant',
 'Dusclops',
 'Dusknoir',
 'Duskull',
 'Dustox',
 'Dwebble',
 'Eelektrik',
 'Eelektross',
 'Eevee',
 'Eiscue',
 'Ekans',
 'Eldegoss',
 'Electabuzz',
 'Electivire',
 'Electrike',
 'Electrode',
 'Elekid',
 'Elgyem',
 'Emboar',
 'Emolga',
 'Empoleon',
 'Enamorus',
 'Entei',
 'Escavalier',
 'Espathra',
 'Espeon',
 'Espurr',
 'Eternatus',
 'Excadrill',
 'Exeggcute',
 'Exeggutor',
 'Exploud',
 'Falinks',
 'Farfetch’d',
 'Farigiraf',
 'Fearow',
 'Feebas',
 'Fennekin',
 'Feraligatr',
 'Ferroseed',
 'Ferrothorn',
 'Fidough',
 'Finizen',
 'Finneon',
 'Flaaffy',
 'Flabébé',
 'Flamigo',
 'Flapple',
 'Flareon',
 'Fletchinder',
 'Fletchling',
 'Flittle',
 'Floatzel',
 'Floette',
 'Floragato',
 'Florges',
 'Flutter Mane',
 'Flygon',
 'Fomantis',
 'Foongus',
 'Forretress',
 'Fraxure',
 'Frigibax',
 'Frillish',
 'Froakie',
 'Frogadier',
 'Froslass',
 'Frosmoth',
 'Fuecoco',
 'Furfrou',
 'Furret',
 'Gabite',
 'Gallade',
 'Galvantula',
 'Garbodor',
 'Garchomp',
 'Gardevoir',
 'Garganacl',
 'Gastly',
 'Gastrodon',
 'Genesect',
 'Gengar',
 'Geodude',
 'Gholdengo',
 'Gible',
 'Gigalith',
 'Gimmighoul',
 'Girafarig',
 'Giratina',
 'Glaceon',
 'Glalie',
 'Glameow',
 'Glastrier',
 'Gligar',
 'Glimmet',
 'Glimmora',
 'Gliscor',
 'Gloom',
 'Gogoat',
 'Golbat',
 'Goldeen',
 'Golduck',
 'Golem',
 'Golett',
 'Golisopod',
 'Golurk',
 'Goodra',
 'Goomy',
 'Gorebyss',
 'Gossifleur',
 'Gothita',
 'Gothitelle',
 'Gothorita',
 'Gourgeist',
 'Grafaiai',
 'Granbull',
 'Grapploct',
 'Graveler',
 'Great Tusk',
 'Greavard',
 'Greedent',
 'Greninja',
 'Grimer',
 'Grimmsnarl',
 'Grookey',
 'Grotle',
 'Groudon',
 'Grovyle',
 'Growlithe',
 'Grubbin',
 'Grumpig',
 'Gulpin',
 'Gumshoos',
 'Gurdurr',
 'Guzzlord',
 'Gyarados',
 'Hakamo-o',
 'Happiny',
 'Hariyama',
 'Hatenna',
 'Hatterene',
 'Hattrem',
 'Haunter',
 'Hawlucha',
 'Haxorus',
 'Heatmor',
 'Heatran',
 'Heliolisk',
 'Helioptile',
 'Heracross',
 'Herdier',
 'Hippopotas',
 'Hippowdon',
 'Hitmonchan',
 'Hitmonlee',
 'Hitmontop',
 'Ho-Oh',
 'Honchkrow',
 'Honedge',
 'Hoopa',
 'Hoothoot',
 'Hoppip',
 'Horsea',
 'Houndoom',
 'Houndour',
 'Houndstone',
 'Huntail',
 'Hydreigon',
 'Hypno',
 'Igglybuff',
 'Illumise',
 'Impidimp',
 'Incineroar',
 'Indeedee',
 'Infernape',
 'Inkay',
 'Inteleon',
 'Iron Bundle',
 'Iron Hands',
 'Iron Jugulis',
 'Iron Leaves',
 'Iron Moth',
 'Iron Thorns',
 'Iron Treads',
 'Iron Valiant',
 'Ivysaur',
 'Jangmo-o',
 'Jellicent',
 'Jigglypuff',
 'Jirachi',
 'Jolteon',
 'Joltik',
 'Jumpluff',
 'Jynx',
 'Kabuto',
 'Kabutops',
 'Kadabra',
 'Kakuna',
 'Kangaskhan',
 'Karrablast',
 'Kartana',
 'Kecleon',
 'Keldeo',
 'Kilowattrel',
 'Kingambit',
 'Kingdra',
 'Kingler',
 'Kirlia',
 'Klang',
 'Klawf',
 'Kleavor',
 'Klefki',
 'Klink',
 'Klinklang',
 'Koffing',
 'Komala',
 'Kommo-o',
 'Koraidon',
 'Krabby',
 'Kricketot',
 'Kricketune',
 'Krokorok',
 'Krookodile',
 'Kubfu',
 'Kyogre',
 'Kyurem',
 'Lairon',
 'Lampent',
 'Landorus',
 'Lanturn',
 'Lapras',
 'Larvesta',
 'Larvitar',
 'Latias',
 'Latios',
 'Leafeon',
 'Leavanny',
 'Lechonk',
 'Ledian',
 'Ledyba',
 'Lickilicky',
 'Lickitung',
 'Liepard',
 'Lileep',
 'Lilligant',
 'Lillipup',
 'Linoone',
 'Litleo',
 'Litten',
 'Litwick',
 'Lokix',
 'Lombre',
 'Lopunny',
 'Lotad',
 'Loudred',
 'Lucario',
 'Ludicolo',
 'Lugia',
 'Lumineon',
 'Lunala',
 'Lunatone',
 'Lurantis',
 'Luvdisc',
 'Luxio',
 'Luxray',
 'Lycanroc',
 'Mabosstiff',
 'Machamp',
 'Machoke',
 'Machop',
 'Magby',
 'Magcargo',
 'Magearna',
 'Magikarp',
 'Magmar',
 'Magmortar',
 'Magnemite',
 'Magneton',
 'Magnezone',
 'Makuhita',
 'Malamar',
 'Mamoswine',
 'Manaphy',
 'Mandibuzz',
 'Manectric',
 'Mankey',
 'Mantine',
 'Mantyke',
 'Maractus',
 'Mareanie',
 'Mareep',
 'Marill',
 'Marowak',
 'Marshadow',
 'Marshtomp',
 'Maschiff',
 'Masquerain',
 'Maushold',
 'Mawile',
 'Medicham',
 'Meditite',
 'Meganium',
 'Melmetal',
 'Meloetta',
 'Meltan',
 'Meowscarada',
 'Meowstic',
 'Meowth',
 'Mesprit',
 'Metagross',
 'Metang',
 'Metapod',
 'Mew',
 'Mewtwo',
 'Mienfoo',
 'Mienshao',
 'Mightyena',
 'Milcery',
 'Milotic',
 'Miltank',
 'Mime Jr.',
 'Mimikyu',
 'Minccino',
 'Minior',
 'Minun',
 'Miraidon',
 'Misdreavus',
 'Mismagius',
 'Moltres',
 'Monferno',
 'Morelull',
 'Morgrem',
 'Morpeko',
 'Mothim',
 'Mr. Mime',
 'Mr. Rime',
 'Mudbray',
 'Mudkip',
 'Mudsdale',
 'Muk',
 'Munchlax',
 'Munna',
 'Murkrow',
 'Musharna',
 'Nacli',
 'Naclstack',
 'Naganadel',
 'Natu',
 'Necrozma',
 'Nickit',
 'Nidoking',
 'Nidoqueen',
 'Nidoran♀',
 'Nidoran♂',
 'Nidorina',
 'Nidorino',
 'Nihilego',
 'Nincada',
 'Ninetales',
 'Ninjask',
 'Noctowl',
 'Noibat',
 'Noivern',
 'Nosepass',
 'Numel',
 'Nuzleaf',
 'Nymble',
 'Obstagoon',
 'Octillery',
 'Oddish',
 'Oinkologne',
 'Omanyte',
 'Omastar',
 'Onix',
 'Oranguru',
 'Orbeetle',
 'Oricorio',
 'Orthworm',
 'Oshawott',
 'Overqwil',
 'Pachirisu',
 'Palafin',
 'Palkia',
 'Palossand',
 'Palpitoad',
 'Pancham',
 'Pangoro',
 'Panpour',
 'Pansage',
 'Pansear',
 'Paras',
 'Parasect',
 'Passimian',
 'Patrat',
 'Pawmi',
 'Pawmo',
 'Pawmot',
 'Pawniard',
 'Pelipper',
 'Perrserker',
 'Persian',
 'Petilil',
 'Phanpy',
 'Phantump',
 'Pheromosa',
 'Phione',
 'Pichu',
 'Pidgeot',
 'Pidgeotto',
 'Pidgey',
 'Pidove',
 'Pignite',
 'Pikachu',
 'Pikipek',
 'Piloswine',
 'Pincurchin',
 'Pineco',
 'Pinsir',
 'Piplup',
 'Plusle',
 'Poipole',
 'Politoed',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Polteageist',
 'Ponyta',
 'Poochyena',
 'Popplio',
 'Porygon',
 'Porygon-Z',
 'Porygon2',
 'Primarina',
 'Primeape',
 'Prinplup',
 'Probopass',
 'Psyduck',
 'Pumpkaboo',
 'Pupitar',
 'Purrloin',
 'Purugly',
 'Pyroar',
 'Pyukumuku',
 'Quagsire',
 'Quaquaval',
 'Quaxly',
 'Quaxwell',
 'Quilava',
 'Quilladin',
 'Qwilfish',
 'Raboot',
 'Rabsca',
 'Raichu',
 'Raikou',
 'Ralts',
 'Rampardos',
 'Rapidash',
 'Raticate',
 'Rattata',
 'Rayquaza',
 'Regice',
 'Regidrago',
 'Regieleki',
 'Regigigas',
 'Regirock',
 'Registeel',
 'Relicanth',
 'Rellor',
 'Remoraid',
 'Reshiram',
 'Reuniclus',
 'Revavroom',
 'Rhydon',
 'Rhyhorn',
 'Rhyperior',
 'Ribombee',
 'Rillaboom',
 'Riolu',
 'Roaring Moon',
 'Rockruff',
 'Roggenrola',
 'Rolycoly',
 'Rookidee',
 'Roselia',
 'Roserade',
 'Rotom',
 'Rowlet',
 'Rufflet',
 'Runerigus',
 'Sableye',
 'Salamence',
 'Salandit',
 'Salazzle',
 'Samurott',
 'Sandaconda',
 'Sandile',
 'Sandshrew',
 'Sandslash',
 'Sandy Shocks',
 'Sandygast',
 'Sawk',
 'Sawsbuck',
 'Scatterbug',
 'Sceptile',
 'Scizor',
 'Scolipede',
 'Scorbunny',
 'Scovillain',
 'Scrafty',
 'Scraggy',
 'Scream Tail',
 'Scyther',
 'Seadra',
 'Seaking',
 'Sealeo',
 'Seedot',
 'Seel',
 'Seismitoad',
 'Sentret',
 'Serperior',
 'Servine',
 'Seviper',
 'Sewaddle',
 'Sharpedo',
 'Shaymin',
 'Shedinja',
 'Shelgon',
 'Shellder',
 'Shellos',
 'Shelmet',
 'Shieldon',
 'Shiftry',
 'Shiinotic',
 'Shinx',
 'Shroodle',
 'Shroomish',
 'Shuckle',
 'Shuppet',
 'Sigilyph',
 'Silcoon',
 'Silicobra',
 'Silvally',
 'Simipour',
 'Simisage',
 'Simisear',
 'Sinistea',
 'Sirfetch’d',
 'Sizzlipede',
 'Skarmory',
 'Skeledirge',
 'Skiddo',
 'Skiploom',
 'Skitty',
 'Skorupi',
 'Skrelp',
 'Skuntank',
 'Skwovet',
 'Slaking',
 'Slakoth',
 'Sliggoo',
 'Slither Wing',
 'Slowbro',
 'Slowking',
 'Slowpoke',
 'Slugma',
 'Slurpuff',
 'Smeargle',
 'Smoliv',
 'Smoochum',
 'Sneasel',
 'Sneasler',
 'Snivy',
 'Snom',
 'Snorlax',
 'Snorunt',
 'Snover',
 'Snubbull',
 'Sobble',
 'Solgaleo',
 'Solosis',
 'Solrock',
 'Spearow',
 'Spectrier',
 'Spewpa',
 'Spheal',
 'Spidops',
 'Spinarak',
 'Spinda',
 'Spiritomb',
 'Spoink',
 'Sprigatito',
 'Spritzee',
 'Squawkabilly',
 'Squirtle',
 'Stakataka',
 'Stantler',
 'Staraptor',
 'Staravia',
 'Starly',
 'Starmie',
 'Staryu',
 'Steelix',
 'Steenee',
 'Stonjourner',
 'Stoutland',
 'Stufful',
 'Stunfisk',
 'Stunky',
 'Sudowoodo',
 'Suicune',
 'Sunflora',
 'Sunkern',
 'Surskit',
 'Swablu',
 'Swadloon',
 'Swalot',
 'Swampert',
 'Swanna',
 'Swellow',
 'Swinub',
 'Swirlix',
 'Swoobat',
 'Sylveon',
 'Tadbulb',
 'Taillow',
 'Talonflame',
 'Tandemaus',
 'Tangela',
 'Tangrowth',
 'Tapu Bulu',
 'Tapu Fini',
 'Tapu Koko',
 'Tapu Lele',
 'Tarountula',
 'Tatsugiri',
 'Tauros',
 'Teddiursa',
 'Tentacool',
 'Tentacruel',
 'Tepig',
 'Terrakion',
 'Thievul',
 'Throh',
 'Thundurus',
 'Thwackey',
 'Timburr',
 'Ting-Lu',
 'Tinkatink',
 'Tinkaton',
 'Tinkatuff',
 'Tirtouga',
 'Toedscool',
 'Toedscruel',
 'Togedemaru',
 'Togekiss',
 'Togepi',
 'Togetic',
 'Torchic',
 'Torkoal',
 'Tornadus',
 'Torracat',
 'Torterra',
 'Totodile',
 'Toucannon',
 'Toxapex',
 'Toxel',
 'Toxicroak',
 'Toxtricity',
 'Tranquill',
 'Trapinch',
 'Treecko',
 'Trevenant',
 'Tropius',
 'Trubbish',
 'Trumbeak',
 'Tsareena',
 'Turtonator',
 'Turtwig',
 'Tympole',
 'Tynamo',
 'Type: Null',
 'Typhlosion',
 'Tyranitar',
 'Tyrantrum',
 'Tyrogue',
 'Tyrunt',
 'Umbreon',
 'Unfezant',
 'Unown',
 'Ursaluna',
 'Ursaring',
 'Urshifu',
 'Uxie',
 'Vanillish',
 'Vanillite',
 'Vanilluxe',
 'Vaporeon',
 'Varoom',
 'Veluza',
 'Venipede',
 'Venomoth',
 'Venonat',
 'Venusaur',
 'Vespiquen',
 'Vibrava',
 'Victini',
 'Victreebel',
 'Vigoroth',
 'Vikavolt',
 'Vileplume',
 'Virizion',
 'Vivillon',
 'Volbeat',
 'Volcanion',
 'Volcarona',
 'Voltorb',
 'Vullaby',
 'Vulpix',
 'Wailmer',
 'Wailord',
 'Walking Wake',
 'Walrein',
 'Wartortle',
 'Watchog',
 'Wattrel',
 'Weavile',
 'Weedle',
 'Weepinbell',
 'Weezing',
 'Whimsicott',
 'Whirlipede',
 'Whiscash',
 'Whismur',
 'Wigglytuff',
 'Wiglett',
 'Wimpod',
 'Wingull',
 'Wishiwashi',
 'Wo-Chien',
 'Wobbuffet',
 'Woobat',
 'Wooloo',
 'Wooper',
 'Wormadam',
 'Wugtrio',
 'Wurmple',
 'Wynaut',
 'Wyrdeer',
 'Xatu',
 'Xerneas',
 'Xurkitree',
 'Yamask',
 'Yamper',
 'Yanma',
 'Yanmega',
 'Yungoos',
 'Yveltal',
 'Zacian',
 'Zamazenta',
 'Zangoose',
 'Zapdos',
 ...]

In [35]:
dict(pokemon)

{0: 'Bulbasaur',
 1: 'Ivysaur',
 2: 'Venusaur',
 3: 'Charmander',
 4: 'Charmeleon',
 5: 'Charizard',
 6: 'Squirtle',
 7: 'Wartortle',
 8: 'Blastoise',
 9: 'Caterpie',
 10: 'Metapod',
 11: 'Butterfree',
 12: 'Weedle',
 13: 'Kakuna',
 14: 'Beedrill',
 15: 'Pidgey',
 16: 'Pidgeotto',
 17: 'Pidgeot',
 18: 'Rattata',
 19: 'Raticate',
 20: 'Spearow',
 21: 'Fearow',
 22: 'Ekans',
 23: 'Arbok',
 24: 'Pikachu',
 25: 'Raichu',
 26: 'Sandshrew',
 27: 'Sandslash',
 28: 'Nidoran♀',
 29: 'Nidorina',
 30: 'Nidoqueen',
 31: 'Nidoran♂',
 32: 'Nidorino',
 33: 'Nidoking',
 34: 'Clefairy',
 35: 'Clefable',
 36: 'Vulpix',
 37: 'Ninetales',
 38: 'Jigglypuff',
 39: 'Wigglytuff',
 40: 'Zubat',
 41: 'Golbat',
 42: 'Oddish',
 43: 'Gloom',
 44: 'Vileplume',
 45: 'Paras',
 46: 'Parasect',
 47: 'Venonat',
 48: 'Venomoth',
 49: 'Diglett',
 50: 'Dugtrio',
 51: 'Meowth',
 52: 'Persian',
 53: 'Psyduck',
 54: 'Golduck',
 55: 'Mankey',
 56: 'Primeape',
 57: 'Growlithe',
 58: 'Arcanine',
 59: 'Poliwag',
 60: 'Poliwhirl',
 61: 'Poliwrath',
 62: 'Abra',
 63: 'Kadabra',
 64: 'Alakazam',
 65: 'Machop',
 66: 'Machoke',
 67: 'Machamp',
 68: 'Bellsprout',
 69: 'Weepinbell',
 70: 'Victreebel',
 71: 'Tentacool',
 72: 'Tentacruel',
 73: 'Geodude',
 74: 'Graveler',
 75: 'Golem',
 76: 'Ponyta',
 77: 'Rapidash',
 78: 'Slowpoke',
 79: 'Slowbro',
 80: 'Magnemite',
 81: 'Magneton',
 82: 'Farfetch’d',
 83: 'Doduo',
 84: 'Dodrio',
 85: 'Seel',
 86: 'Dewgong',
 87: 'Grimer',
 88: 'Muk',
 89: 'Shellder',
 90: 'Cloyster',
 91: 'Gastly',
 92: 'Haunter',
 93: 'Gengar',
 94: 'Onix',
 95: 'Drowzee',
 96: 'Hypno',
 97: 'Krabby',
 98: 'Kingler',
 99: 'Voltorb',
 100: 'Electrode',
 101: 'Exeggcute',
 102: 'Exeggutor',
 103: 'Cubone',
 104: 'Marowak',
 105: 'Hitmonlee',
 106: 'Hitmonchan',
 107: 'Lickitung',
 108: 'Koffing',
 109: 'Weezing',
 110: 'Rhyhorn',
 111: 'Rhydon',
 112: 'Chansey',
 113: 'Tangela',
 114: 'Kangaskhan',
 115: 'Horsea',
 116: 'Seadra',
 117: 'Goldeen',
 118: 'Seaking',
 119: 'Staryu',
 120: 'Starmie',
 121: 'Mr. Mime',
 122: 'Scyther',
 123: 'Jynx',
 124: 'Electabuzz',
 125: 'Magmar',
 126: 'Pinsir',
 127: 'Tauros',
 128: 'Magikarp',
 129: 'Gyarados',
 130: 'Lapras',
 131: 'Ditto',
 132: 'Eevee',
 133: 'Vaporeon',
 134: 'Jolteon',
 135: 'Flareon',
 136: 'Porygon',
 137: 'Omanyte',
 138: 'Omastar',
 139: 'Kabuto',
 140: 'Kabutops',
 141: 'Aerodactyl',
 142: 'Snorlax',
 143: 'Articuno',
 144: 'Zapdos',
 145: 'Moltres',
 146: 'Dratini',
 147: 'Dragonair',
 148: 'Dragonite',
 149: 'Mewtwo',
 150: 'Mew',
 151: 'Chikorita',
 152: 'Bayleef',
 153: 'Meganium',
 154: 'Cyndaquil',
 155: 'Quilava',
 156: 'Typhlosion',
 157: 'Totodile',
 158: 'Croconaw',
 159: 'Feraligatr',
 160: 'Sentret',
 161: 'Furret',
 162: 'Hoothoot',
 163: 'Noctowl',
 164: 'Ledyba',
 165: 'Ledian',
 166: 'Spinarak',
 167: 'Ariados',
 168: 'Crobat',
 169: 'Chinchou',
 170: 'Lanturn',
 171: 'Pichu',
 172: 'Cleffa',
 173: 'Igglybuff',
 174: 'Togepi',
 175: 'Togetic',
 176: 'Natu',
 177: 'Xatu',
 178: 'Mareep',
 179: 'Flaaffy',
 180: 'Ampharos',
 181: 'Bellossom',
 182: 'Marill',
 183: 'Azumarill',
 184: 'Sudowoodo',
 185: 'Politoed',
 186: 'Hoppip',
 187: 'Skiploom',
 188: 'Jumpluff',
 189: 'Aipom',
 190: 'Sunkern',
 191: 'Sunflora',
 192: 'Yanma',
 193: 'Wooper',
 194: 'Quagsire',
 195: 'Espeon',
 196: 'Umbreon',
 197: 'Murkrow',
 198: 'Slowking',
 199: 'Misdreavus',
 200: 'Unown',
 201: 'Wobbuffet',
 202: 'Girafarig',
 203: 'Pineco',
 204: 'Forretress',
 205: 'Dunsparce',
 206: 'Gligar',
 207: 'Steelix',
 208: 'Snubbull',
 209: 'Granbull',
 210: 'Qwilfish',
 211: 'Scizor',
 212: 'Shuckle',
 213: 'Heracross',
 214: 'Sneasel',
 215: 'Teddiursa',
 216: 'Ursaring',
 217: 'Slugma',
 218: 'Magcargo',
 219: 'Swinub',
 220: 'Piloswine',
 221: 'Corsola',
 222: 'Remoraid',
 223: 'Octillery',
 224: 'Delibird',
 225: 'Mantine',
 226: 'Skarmory',
 227: 'Houndour',
 228: 'Houndoom',
 229: 'Kingdra',
 230: 'Phanpy',
 231: 'Donphan',
 232: 'Porygon2',
 233: 'Stantler',
 234: 'Smeargle',
 235: 'Tyrogue',
 236: 'Hitmontop',
 237: 'Smoochum',
 238: 'Elekid',
 239: 'Magby',
 240: 'Miltank',
 241: 'Blissey',
 242: 'Raikou',
 243: 'Entei',
 244: 'Suicune',
 245: 'Larvitar',
 246: 'Pupitar',
 247: 'Tyranitar',
 248: 'Lugia',
 249: 'Ho-Oh',
 250: 'Celebi',
 251: 'Treecko',
 252: 'Grovyle',
 253: 'Sceptile',
 254: 'Torchic',
 255: 'Combusken',
 256: 'Blaziken',
 257: 'Mudkip',
 258: 'Marshtomp',
 259: 'Swampert',
 260: 'Poochyena',
 261: 'Mightyena',
 262: 'Zigzagoon',
 263: 'Linoone',
 264: 'Wurmple',
 265: 'Silcoon',
 266: 'Beautifly',
 267: 'Cascoon',
 268: 'Dustox',
 269: 'Lotad',
 270: 'Lombre',
 271: 'Ludicolo',
 272: 'Seedot',
 273: 'Nuzleaf',
 274: 'Shiftry',
 275: 'Taillow',
 276: 'Swellow',
 277: 'Wingull',
 278: 'Pelipper',
 279: 'Ralts',
 280: 'Kirlia',
 281: 'Gardevoir',
 282: 'Surskit',
 283: 'Masquerain',
 284: 'Shroomish',
 285: 'Breloom',
 286: 'Slakoth',
 287: 'Vigoroth',
 288: 'Slaking',
 289: 'Nincada',
 290: 'Ninjask',
 291: 'Shedinja',
 292: 'Whismur',
 293: 'Loudred',
 294: 'Exploud',
 295: 'Makuhita',
 296: 'Hariyama',
 297: 'Azurill',
 298: 'Nosepass',
 299: 'Skitty',
 300: 'Delcatty',
 301: 'Sableye',
 302: 'Mawile',
 303: 'Aron',
 304: 'Lairon',
 305: 'Aggron',
 306: 'Meditite',
 307: 'Medicham',
 308: 'Electrike',
 309: 'Manectric',
 310: 'Plusle',
 311: 'Minun',
 312: 'Volbeat',
 313: 'Illumise',
 314: 'Roselia',
 315: 'Gulpin',
 316: 'Swalot',
 317: 'Carvanha',
 318: 'Sharpedo',
 319: 'Wailmer',
 320: 'Wailord',
 321: 'Numel',
 322: 'Camerupt',
 323: 'Torkoal',
 324: 'Spoink',
 325: 'Grumpig',
 326: 'Spinda',
 327: 'Trapinch',
 328: 'Vibrava',
 329: 'Flygon',
 330: 'Cacnea',
 331: 'Cacturne',
 332: 'Swablu',
 333: 'Altaria',
 334: 'Zangoose',
 335: 'Seviper',
 336: 'Lunatone',
 337: 'Solrock',
 338: 'Barboach',
 339: 'Whiscash',
 340: 'Corphish',
 341: 'Crawdaunt',
 342: 'Baltoy',
 343: 'Claydol',
 344: 'Lileep',
 345: 'Cradily',
 346: 'Anorith',
 347: 'Armaldo',
 348: 'Feebas',
 349: 'Milotic',
 350: 'Castform',
 351: 'Kecleon',
 352: 'Shuppet',
 353: 'Banette',
 354: 'Duskull',
 355: 'Dusclops',
 356: 'Tropius',
 357: 'Chimecho',
 358: 'Absol',
 359: 'Wynaut',
 360: 'Snorunt',
 361: 'Glalie',
 362: 'Spheal',
 363: 'Sealeo',
 364: 'Walrein',
 365: 'Clamperl',
 366: 'Huntail',
 367: 'Gorebyss',
 368: 'Relicanth',
 369: 'Luvdisc',
 370: 'Bagon',
 371: 'Shelgon',
 372: 'Salamence',
 373: 'Beldum',
 374: 'Metang',
 375: 'Metagross',
 376: 'Regirock',
 377: 'Regice',
 378: 'Registeel',
 379: 'Latias',
 380: 'Latios',
 381: 'Kyogre',
 382: 'Groudon',
 383: 'Rayquaza',
 384: 'Jirachi',
 385: 'Deoxys',
 386: 'Turtwig',
 387: 'Grotle',
 388: 'Torterra',
 389: 'Chimchar',
 390: 'Monferno',
 391: 'Infernape',
 392: 'Piplup',
 393: 'Prinplup',
 394: 'Empoleon',
 395: 'Starly',
 396: 'Staravia',
 397: 'Staraptor',
 398: 'Bidoof',
 399: 'Bibarel',
 400: 'Kricketot',
 401: 'Kricketune',
 402: 'Shinx',
 403: 'Luxio',
 404: 'Luxray',
 405: 'Budew',
 406: 'Roserade',
 407: 'Cranidos',
 408: 'Rampardos',
 409: 'Shieldon',
 410: 'Bastiodon',
 411: 'Burmy',
 412: 'Wormadam',
 413: 'Mothim',
 414: 'Combee',
 415: 'Vespiquen',
 416: 'Pachirisu',
 417: 'Buizel',
 418: 'Floatzel',
 419: 'Cherubi',
 420: 'Cherrim',
 421: 'Shellos',
 422: 'Gastrodon',
 423: 'Ambipom',
 424: 'Drifloon',
 425: 'Drifblim',
 426: 'Buneary',
 427: 'Lopunny',
 428: 'Mismagius',
 429: 'Honchkrow',
 430: 'Glameow',
 431: 'Purugly',
 432: 'Chingling',
 433: 'Stunky',
 434: 'Skuntank',
 435: 'Bronzor',
 436: 'Bronzong',
 437: 'Bonsly',
 438: 'Mime Jr.',
 439: 'Happiny',
 440: 'Chatot',
 441: 'Spiritomb',
 442: 'Gible',
 443: 'Gabite',
 444: 'Garchomp',
 445: 'Munchlax',
 446: 'Riolu',
 447: 'Lucario',
 448: 'Hippopotas',
 449: 'Hippowdon',
 450: 'Skorupi',
 451: 'Drapion',
 452: 'Croagunk',
 453: 'Toxicroak',
 454: 'Carnivine',
 455: 'Finneon',
 456: 'Lumineon',
 457: 'Mantyke',
 458: 'Snover',
 459: 'Abomasnow',
 460: 'Weavile',
 461: 'Magnezone',
 462: 'Lickilicky',
 463: 'Rhyperior',
 464: 'Tangrowth',
 465: 'Electivire',
 466: 'Magmortar',
 467: 'Togekiss',
 468: 'Yanmega',
 469: 'Leafeon',
 470: 'Glaceon',
 471: 'Gliscor',
 472: 'Mamoswine',
 473: 'Porygon-Z',
 474: 'Gallade',
 475: 'Probopass',
 476: 'Dusknoir',
 477: 'Froslass',
 478: 'Rotom',
 479: 'Uxie',
 480: 'Mesprit',
 481: 'Azelf',
 482: 'Dialga',
 483: 'Palkia',
 484: 'Heatran',
 485: 'Regigigas',
 486: 'Giratina',
 487: 'Cresselia',
 488: 'Phione',
 489: 'Manaphy',
 490: 'Darkrai',
 491: 'Shaymin',
 492: 'Arceus',
 493: 'Victini',
 494: 'Snivy',
 495: 'Servine',
 496: 'Serperior',
 497: 'Tepig',
 498: 'Pignite',
 499: 'Emboar',
 500: 'Oshawott',
 501: 'Dewott',
 502: 'Samurott',
 503: 'Patrat',
 504: 'Watchog',
 505: 'Lillipup',
 506: 'Herdier',
 507: 'Stoutland',
 508: 'Purrloin',
 509: 'Liepard',
 510: 'Pansage',
 511: 'Simisage',
 512: 'Pansear',
 513: 'Simisear',
 514: 'Panpour',
 515: 'Simipour',
 516: 'Munna',
 517: 'Musharna',
 518: 'Pidove',
 519: 'Tranquill',
 520: 'Unfezant',
 521: 'Blitzle',
 522: 'Zebstrika',
 523: 'Roggenrola',
 524: 'Boldore',
 525: 'Gigalith',
 526: 'Woobat',
 527: 'Swoobat',
 528: 'Drilbur',
 529: 'Excadrill',
 530: 'Audino',
 531: 'Timburr',
 532: 'Gurdurr',
 533: 'Conkeldurr',
 534: 'Tympole',
 535: 'Palpitoad',
 536: 'Seismitoad',
 537: 'Throh',
 538: 'Sawk',
 539: 'Sewaddle',
 540: 'Swadloon',
 541: 'Leavanny',
 542: 'Venipede',
 543: 'Whirlipede',
 544: 'Scolipede',
 545: 'Cottonee',
 546: 'Whimsicott',
 547: 'Petilil',
 548: 'Lilligant',
 549: 'Basculin',
 550: 'Sandile',
 551: 'Krokorok',
 552: 'Krookodile',
 553: 'Darumaka',
 554: 'Darmanitan',
 555: 'Maractus',
 556: 'Dwebble',
 557: 'Crustle',
 558: 'Scraggy',
 559: 'Scrafty',
 560: 'Sigilyph',
 561: 'Yamask',
 562: 'Cofagrigus',
 563: 'Tirtouga',
 564: 'Carracosta',
 565: 'Archen',
 566: 'Archeops',
 567: 'Trubbish',
 568: 'Garbodor',
 569: 'Zorua',
 570: 'Zoroark',
 571: 'Minccino',
 572: 'Cinccino',
 573: 'Gothita',
 574: 'Gothorita',
 575: 'Gothitelle',
 576: 'Solosis',
 577: 'Duosion',
 578: 'Reuniclus',
 579: 'Ducklett',
 580: 'Swanna',
 581: 'Vanillite',
 582: 'Vanillish',
 583: 'Vanilluxe',
 584: 'Deerling',
 585: 'Sawsbuck',
 586: 'Emolga',
 587: 'Karrablast',
 588: 'Escavalier',
 589: 'Foongus',
 590: 'Amoonguss',
 591: 'Frillish',
 592: 'Jellicent',
 593: 'Alomomola',
 594: 'Joltik',
 595: 'Galvantula',
 596: 'Ferroseed',
 597: 'Ferrothorn',
 598: 'Klink',
 599: 'Klang',
 600: 'Klinklang',
 601: 'Tynamo',
 602: 'Eelektrik',
 603: 'Eelektross',
 604: 'Elgyem',
 605: 'Beheeyem',
 606: 'Litwick',
 607: 'Lampent',
 608: 'Chandelure',
 609: 'Axew',
 610: 'Fraxure',
 611: 'Haxorus',
 612: 'Cubchoo',
 613: 'Beartic',
 614: 'Cryogonal',
 615: 'Shelmet',
 616: 'Accelgor',
 617: 'Stunfisk',
 618: 'Mienfoo',
 619: 'Mienshao',
 620: 'Druddigon',
 621: 'Golett',
 622: 'Golurk',
 623: 'Pawniard',
 624: 'Bisharp',
 625: 'Bouffalant',
 626: 'Rufflet',
 627: 'Braviary',
 628: 'Vullaby',
 629: 'Mandibuzz',
 630: 'Heatmor',
 631: 'Durant',
 632: 'Deino',
 633: 'Zweilous',
 634: 'Hydreigon',
 635: 'Larvesta',
 636: 'Volcarona',
 637: 'Cobalion',
 638: 'Terrakion',
 639: 'Virizion',
 640: 'Tornadus',
 641: 'Thundurus',
 642: 'Reshiram',
 643: 'Zekrom',
 644: 'Landorus',
 645: 'Kyurem',
 646: 'Keldeo',
 647: 'Meloetta',
 648: 'Genesect',
 649: 'Chespin',
 650: 'Quilladin',
 651: 'Chesnaught',
 652: 'Fennekin',
 653: 'Braixen',
 654: 'Delphox',
 655: 'Froakie',
 656: 'Frogadier',
 657: 'Greninja',
 658: 'Bunnelby',
 659: 'Diggersby',
 660: 'Fletchling',
 661: 'Fletchinder',
 662: 'Talonflame',
 663: 'Scatterbug',
 664: 'Spewpa',
 665: 'Vivillon',
 666: 'Litleo',
 667: 'Pyroar',
 668: 'Flabébé',
 669: 'Floette',
 670: 'Florges',
 671: 'Skiddo',
 672: 'Gogoat',
 673: 'Pancham',
 674: 'Pangoro',
 675: 'Furfrou',
 676: 'Espurr',
 677: 'Meowstic',
 678: 'Honedge',
 679: 'Doublade',
 680: 'Aegislash',
 681: 'Spritzee',
 682: 'Aromatisse',
 683: 'Swirlix',
 684: 'Slurpuff',
 685: 'Inkay',
 686: 'Malamar',
 687: 'Binacle',
 688: 'Barbaracle',
 689: 'Skrelp',
 690: 'Dragalge',
 691: 'Clauncher',
 692: 'Clawitzer',
 693: 'Helioptile',
 694: 'Heliolisk',
 695: 'Tyrunt',
 696: 'Tyrantrum',
 697: 'Amaura',
 698: 'Aurorus',
 699: 'Sylveon',
 700: 'Hawlucha',
 701: 'Dedenne',
 702: 'Carbink',
 703: 'Goomy',
 704: 'Sliggoo',
 705: 'Goodra',
 706: 'Klefki',
 707: 'Phantump',
 708: 'Trevenant',
 709: 'Pumpkaboo',
 710: 'Gourgeist',
 711: 'Bergmite',
 712: 'Avalugg',
 713: 'Noibat',
 714: 'Noivern',
 715: 'Xerneas',
 716: 'Yveltal',
 717: 'Zygarde',
 718: 'Diancie',
 719: 'Hoopa',
 720: 'Volcanion',
 721: 'Rowlet',
 722: 'Dartrix',
 723: 'Decidueye',
 724: 'Litten',
 725: 'Torracat',
 726: 'Incineroar',
 727: 'Popplio',
 728: 'Brionne',
 729: 'Primarina',
 730: 'Pikipek',
 731: 'Trumbeak',
 732: 'Toucannon',
 733: 'Yungoos',
 734: 'Gumshoos',
 735: 'Grubbin',
 736: 'Charjabug',
 737: 'Vikavolt',
 738: 'Crabrawler',
 739: 'Crabominable',
 740: 'Oricorio',
 741: 'Cutiefly',
 742: 'Ribombee',
 743: 'Rockruff',
 744: 'Lycanroc',
 745: 'Wishiwashi',
 746: 'Mareanie',
 747: 'Toxapex',
 748: 'Mudbray',
 749: 'Mudsdale',
 750: 'Dewpider',
 751: 'Araquanid',
 752: 'Fomantis',
 753: 'Lurantis',
 754: 'Morelull',
 755: 'Shiinotic',
 756: 'Salandit',
 757: 'Salazzle',
 758: 'Stufful',
 759: 'Bewear',
 760: 'Bounsweet',
 761: 'Steenee',
 762: 'Tsareena',
 763: 'Comfey',
 764: 'Oranguru',
 765: 'Passimian',
 766: 'Wimpod',
 767: 'Golisopod',
 768: 'Sandygast',
 769: 'Palossand',
 770: 'Pyukumuku',
 771: 'Type: Null',
 772: 'Silvally',
 773: 'Minior',
 774: 'Komala',
 775: 'Turtonator',
 776: 'Togedemaru',
 777: 'Mimikyu',
 778: 'Bruxish',
 779: 'Drampa',
 780: 'Dhelmise',
 781: 'Jangmo-o',
 782: 'Hakamo-o',
 783: 'Kommo-o',
 784: 'Tapu Koko',
 785: 'Tapu Lele',
 786: 'Tapu Bulu',
 787: 'Tapu Fini',
 788: 'Cosmog',
 789: 'Cosmoem',
 790: 'Solgaleo',
 791: 'Lunala',
 792: 'Nihilego',
 793: 'Buzzwole',
 794: 'Pheromosa',
 795: 'Xurkitree',
 796: 'Celesteela',
 797: 'Kartana',
 798: 'Guzzlord',
 799: 'Necrozma',
 800: 'Magearna',
 801: 'Marshadow',
 802: 'Poipole',
 803: 'Naganadel',
 804: 'Stakataka',
 805: 'Blacephalon',
 806: 'Zeraora',
 807: 'Meltan',
 808: 'Melmetal',
 809: 'Grookey',
 810: 'Thwackey',
 811: 'Rillaboom',
 812: 'Scorbunny',
 813: 'Raboot',
 814: 'Cinderace',
 815: 'Sobble',
 816: 'Drizzile',
 817: 'Inteleon',
 818: 'Skwovet',
 819: 'Greedent',
 820: 'Rookidee',
 821: 'Corvisquire',
 822: 'Corviknight',
 823: 'Blipbug',
 824: 'Dottler',
 825: 'Orbeetle',
 826: 'Nickit',
 827: 'Thievul',
 828: 'Gossifleur',
 829: 'Eldegoss',
 830: 'Wooloo',
 831: 'Dubwool',
 832: 'Chewtle',
 833: 'Drednaw',
 834: 'Yamper',
 835: 'Boltund',
 836: 'Rolycoly',
 837: 'Carkol',
 838: 'Coalossal',
 839: 'Applin',
 840: 'Flapple',
 841: 'Appletun',
 842: 'Silicobra',
 843: 'Sandaconda',
 844: 'Cramorant',
 845: 'Arrokuda',
 846: 'Barraskewda',
 847: 'Toxel',
 848: 'Toxtricity',
 849: 'Sizzlipede',
 850: 'Centiskorch',
 851: 'Clobbopus',
 852: 'Grapploct',
 853: 'Sinistea',
 854: 'Polteageist',
 855: 'Hatenna',
 856: 'Hattrem',
 857: 'Hatterene',
 858: 'Impidimp',
 859: 'Morgrem',
 860: 'Grimmsnarl',
 861: 'Obstagoon',
 862: 'Perrserker',
 863: 'Cursola',
 864: 'Sirfetch’d',
 865: 'Mr. Rime',
 866: 'Runerigus',
 867: 'Milcery',
 868: 'Alcremie',
 869: 'Falinks',
 870: 'Pincurchin',
 871: 'Snom',
 872: 'Frosmoth',
 873: 'Stonjourner',
 874: 'Eiscue',
 875: 'Indeedee',
 876: 'Morpeko',
 877: 'Cufant',
 878: 'Copperajah',
 879: 'Dracozolt',
 880: 'Arctozolt',
 881: 'Dracovish',
 882: 'Arctovish',
 883: 'Duraludon',
 884: 'Dreepy',
 885: 'Drakloak',
 886: 'Dragapult',
 887: 'Zacian',
 888: 'Zamazenta',
 889: 'Eternatus',
 890: 'Kubfu',
 891: 'Urshifu',
 892: 'Zarude',
 893: 'Regieleki',
 894: 'Regidrago',
 895: 'Glastrier',
 896: 'Spectrier',
 897: 'Calyrex',
 898: 'Wyrdeer',
 899: 'Kleavor',
 900: 'Ursaluna',
 901: 'Basculegion',
 902: 'Sneasler',
 903: 'Overqwil',
 904: 'Enamorus',
 905: 'Sprigatito',
 906: 'Floragato',
 907: 'Meowscarada',
 908: 'Fuecoco',
 909: 'Crocalor',
 910: 'Skeledirge',
 911: 'Quaxly',
 912: 'Quaxwell',
 913: 'Quaquaval',
 914: 'Lechonk',
 915: 'Oinkologne',
 916: 'Tarountula',
 917: 'Spidops',
 918: 'Nymble',
 919: 'Lokix',
 920: 'Pawmi',
 921: 'Pawmo',
 922: 'Pawmot',
 923: 'Tandemaus',
 924: 'Maushold',
 925: 'Fidough',
 926: 'Dachsbun',
 927: 'Smoliv',
 928: 'Dolliv',
 929: 'Arboliva',
 930: 'Squawkabilly',
 931: 'Nacli',
 932: 'Naclstack',
 933: 'Garganacl',
 934: 'Charcadet',
 935: 'Armarouge',
 936: 'Ceruledge',
 937: 'Tadbulb',
 938: 'Bellibolt',
 939: 'Wattrel',
 940: 'Kilowattrel',
 941: 'Maschiff',
 942: 'Mabosstiff',
 943: 'Shroodle',
 944: 'Grafaiai',
 945: 'Bramblin',
 946: 'Brambleghast',
 947: 'Toedscool',
 948: 'Toedscruel',
 949: 'Klawf',
 950: 'Capsakid',
 951: 'Scovillain',
 952: 'Rellor',
 953: 'Rabsca',
 954: 'Flittle',
 955: 'Espathra',
 956: 'Tinkatink',
 957: 'Tinkatuff',
 958: 'Tinkaton',
 959: 'Wiglett',
 960: 'Wugtrio',
 961: 'Bombirdier',
 962: 'Finizen',
 963: 'Palafin',
 964: 'Varoom',
 965: 'Revavroom',
 966: 'Cyclizar',
 967: 'Orthworm',
 968: 'Glimmet',
 969: 'Glimmora',
 970: 'Greavard',
 971: 'Houndstone',
 972: 'Flamigo',
 973: 'Cetoddle',
 974: 'Cetitan',
 975: 'Veluza',
 976: 'Dondozo',
 977: 'Tatsugiri',
 978: 'Annihilape',
 979: 'Clodsire',
 980: 'Farigiraf',
 981: 'Dudunsparce',
 982: 'Kingambit',
 983: 'Great Tusk',
 984: 'Scream Tail',
 985: 'Brute Bonnet',
 986: 'Flutter Mane',
 987: 'Slither Wing',
 988: 'Sandy Shocks',
 989: 'Iron Treads',
 990: 'Iron Bundle',
 991: 'Iron Hands',
 992: 'Iron Jugulis',
 993: 'Iron Moth',
 994: 'Iron Thorns',
 995: 'Frigibax',
 996: 'Arctibax',
 997: 'Baxcalibur',
 998: 'Gimmighoul',
 999: 'Gholdengo',
 ...}

In [36]:
max(google)

151.863495

In [37]:
"Kakuna" in pokemon.values  # defaults to searching the index, so we need to specify that we want to search the values

True

In [38]:
google.sort_values()

10        2.470490
0         2.490664
13        2.509095
11        2.514326
1         2.515820
           ...
4336    150.000000
4341    150.000000
4346    150.141754
4345    151.000000
4395    151.863495
Name: Price, Length: 4793, dtype: float64

In [39]:
google.sort_index()

0         2.490664
1         2.515820
2         2.758411
3         2.770615
4         2.614201
           ...
4788    132.080002
4789    132.998001
4790    135.570007
4791    137.050003
4792    138.429993
Name: Price, Length: 4793, dtype: float64

In [40]:
google.sort_values(ascending=False)

4395    151.863495
4345    151.000000
4346    150.141754
4341    150.000000
4336    150.000000
           ...
1         2.515820
11        2.514326
13        2.509095
0         2.490664
10        2.470490
Name: Price, Length: 4793, dtype: float64

In [41]:
pokemon = pd.read_csv("data/pokemon.csv", index_col='Name', usecols=['Name','Type']).squeeze("columns")

In [42]:
pokemon.sort_values()

Name
Wurmple                Bug
Accelgor               Bug
Shelmet                Bug
Illumise               Bug
Cascoon                Bug
                  ...
Drednaw        Water, Rock
Tirtouga       Water, Rock
Relicanth      Water, Rock
Carracosta     Water, Rock
Empoleon      Water, Steel
Name: Type, Length: 1010, dtype: str

In [43]:
pokemon.sort_index()

Name
Abomasnow        Grass, Ice
Abra                Psychic
Absol                  Dark
Accelgor                Bug
Aegislash      Steel, Ghost
                  ...
Zoroark                Dark
Zorua                  Dark
Zubat        Poison, Flying
Zweilous       Dark, Dragon
Zygarde      Dragon, Ground
Name: Type, Length: 1010, dtype: str

In [44]:
pokemon

Name
Bulbasaur          Grass, Poison
Ivysaur            Grass, Poison
Venusaur           Grass, Poison
Charmander                  Fire
Charmeleon                  Fire
                      ...
Iron Valiant     Fairy, Fighting
Koraidon        Fighting, Dragon
Miraidon        Electric, Dragon
Walking Wake       Water, Dragon
Iron Leaves       Grass, Psychic
Name: Type, Length: 1010, dtype: str

In [45]:
# Extract Series Values by Index Position
pokemon.iloc[3] # returns the value at row 4
pokemon.iloc[0:3] # returns the values at rows 1-4 (the stop index is exclusive)
pokemon.iloc[-1] # returns the value at the last row
pokemon.iloc[-3] # returns the values at the last 3rd rows
pokemon.iloc[-3:] # returns the values at the last 3 rows   
pokemon.iloc[:-3] # returns the values at all rows except the last 3
pokemon.iloc[:4] # returns the values of first 4 rows
pokemon.iloc[[2,4,6]] # returns the values at rows 3,5,7

Name
Venusaur      Grass, Poison
Charmeleon             Fire
Squirtle              Water
Name: Type, dtype: str

In [46]:
# Extract Series Values by Index Label
pokemon.loc["Bulbasaur"] # returns the value at index label "Bulbasaur"
pokemon["Bulbasaur"] # returns the value at index label "Bulbasaur"
pokemon.loc[["Bulbasaur","Charmander","Squirtle"]] # returns the values at index labels "Bulbasaur", "Charmander", and "Squirtle"
pokemon[["Bulbasaur","Charmander","Squirtle"]] # returns the values at index labels "Bulbasaur", "Charmander", and "Squirtle"

pokemon.get("Bulbasaur") # returns the value at index label "Bulbasaur"
pokemon.get(["Bulbasaur","Charmander","Squirtle"]) # returns the values at index labels "Bulbasaur", "Charmander", and "Squirtle"
pokemon.get("Pika", "Not Found") # returns "Not Found" since "Pika" is not an index label in the Series
pokemon.get("Pika") # returns NaN since "Pika" is not an index label in the Series
pokemon.get(["Bulbasaur","Charmander","Squirtle","Pika"], "Not Found") # returns the values at index labels "Bulbasaur", "Charmander", and "Squirtle", and "Not Found" for "Pika" since it is not an index label in the Series

'Not Found'

In [47]:
# Overwrite a Series Value
pokemon.loc["Bulbasaur"] = "Grass/Poison"
pokemon.loc["Bulbasaur"]

'Grass/Poison'

In [48]:
pokemon.iloc[0] = "Grass, Poison"
pokemon.iloc[0]

'Grass, Poison'

In [49]:
pokemon.iloc[[1,2,4]] = ["Fire", "Water", "Bug"]
pokemon.iloc[[1,2,4]]

Name
Ivysaur        Fire
Venusaur      Water
Charmeleon      Bug
Name: Type, dtype: str

In [50]:
# Math Methods on Series Objects
google

0         2.490664
1         2.515820
2         2.758411
3         2.770615
4         2.614201
           ...
4788    132.080002
4789    132.998001
4790    135.570007
4791    137.050003
4792    138.429993
Name: Price, Length: 4793, dtype: float64

In [51]:
google.count() # returns the number of non-missing values in the Series
google.size # returns the total number of values in the Series, including missing values

4793

In [52]:
google.sum() # returns the sum of the values in the Series, excluding missing values

np.float64(192733.129338)

In [53]:
google.product() # returns the product of the values in the Series, excluding missing values

/home/samlau/Python/ML-Projects-and-tutorials/.venv/lib/python3.12/site-packages/numpy/_core/_methods.py:53: RuntimeWarning: overflow encountered in reduce
  return umr_prod(a, axis, dtype, out, keepdims, initial, where)

np.float64(inf)

In [54]:
google.mean() # returns the mean of the values in the Series, excluding missing values

np.float64(40.211376870018775)

In [55]:
google.std() # returns the standard deviation of the values in the Series, excluding missing values

np.float64(37.274752943868094)

In [56]:
google.max() # returns the maximum value in the Series, excluding missing values

np.float64(151.863495)

In [57]:
google.median() # returns the median of the values in the Series, excluding missing values

np.float64(26.327717)

In [58]:
google.mode() # returns the mode of the values in the Series, excluding missing values

0    14.719826
1    49.000000
Name: Price, dtype: float64

In [59]:
google.describe() # returns a summary of statistics for the values in the Series, excluding missing values

count    4793.000000
mean       40.211377
std        37.274753
min         2.470490
25%        12.767395
50%        26.327717
75%        56.311001
max       151.863495
Name: Price, dtype: float64

In [60]:
google

0         2.490664
1         2.515820
2         2.758411
3         2.770615
4         2.614201
           ...
4788    132.080002
4789    132.998001
4790    135.570007
4791    137.050003
4792    138.429993
Name: Price, Length: 4793, dtype: float64

In [61]:
# Broadcasting - the ability of pandas to perform operations on Series and DataFrame objects that have different shapes and sizes. 
# When performing an operation between two Series or DataFrame objects, pandas will automatically align the data based on the index labels 
# and perform the operation element-wise. If one of the Series or DataFrame objects has a smaller shape than the other, pandas will "broadcast" 
# the smaller object across the larger object to perform the operation. 
# This allows for efficient and flexible data manipulation without having to manually reshape or align the data.

google + 10 # adds 10 to each value in the Series, broadcasting the scalar value across the Series

0        12.490664
1        12.515820
2        12.758411
3        12.770615
4        12.614201
           ...
4788    142.080002
4789    142.998001
4790    145.570007
4791    147.050003
4792    148.429993
Name: Price, Length: 4793, dtype: float64

In [62]:
google - 10 # subtracts 10 from each value in the Series, broadcasting the scalar value across the Series

0        -7.509336
1        -7.484180
2        -7.241589
3        -7.229385
4        -7.385799
           ...
4788    122.080002
4789    122.998001
4790    125.570007
4791    127.050003
4792    128.429993
Name: Price, Length: 4793, dtype: float64

In [63]:
google * 2 # multiplies each value in the Series by 2, broadcasting the scalar value across the Series

0         4.981328
1         5.031640
2         5.516822
3         5.541230
4         5.228402
           ...
4788    264.160004
4789    265.996002
4790    271.140014
4791    274.100006
4792    276.859986
Name: Price, Length: 4793, dtype: float64

In [64]:
google / 2 # divides each value in the Series by 2, broadcasting the scalar value across the Series

0        1.245332
1        1.257910
2        1.379206
3        1.385307
4        1.307100
          ...
4788    66.040001
4789    66.499000
4790    67.785004
4791    68.525002
4792    69.214996
Name: Price, Length: 4793, dtype: float64

In [65]:
# Values Count - the number of occurrences of each unique value in the Series. This can be useful for understanding the distribution 
# of values in the Series and identifying any patterns or trends in the data. The value_counts() method returns a Series containing 
# counts of unique values in the original Series, sorted in descending order by default.

pokemon.value_counts()

Type
Water               75
Normal              74
Grass               46
Psychic             39
Fire                36
                    ..
Rock, Electric       1
Dark, Ground         1
Dragon, Dark         1
Fairy, Fighting      1
Fighting, Dragon     1
Name: count, Length: 200, dtype: int64

In [66]:
pokemon.value_counts(normalize=True) # returns the relative frequencies of each unique value in the Series, normalized to sum to 1

Type
Water               0.074257
Normal              0.073267
Grass               0.045545
Psychic             0.038614
Fire                0.035644
                      ...
Rock, Electric      0.000990
Dark, Ground        0.000990
Dragon, Dark        0.000990
Fairy, Fighting     0.000990
Fighting, Dragon    0.000990
Name: proportion, Length: 200, dtype: float64

In [67]:
# The apply() method allows you to apply a function to each element in the Series. This can be useful for performing custom 
# transformations or calculations on the data.

pokemon

Name
Bulbasaur          Grass, Poison
Ivysaur                     Fire
Venusaur                   Water
Charmander                  Fire
Charmeleon                   Bug
                      ...
Iron Valiant     Fairy, Fighting
Koraidon        Fighting, Dragon
Miraidon        Electric, Dragon
Walking Wake       Water, Dragon
Iron Leaves       Grass, Psychic
Name: Type, Length: 1010, dtype: str

In [68]:
pokemon.apply(len) # applies the len() function to each value in the Series, returning a new Series with the lengths of each value

Name
Bulbasaur       13
Ivysaur          4
Venusaur         5
Charmander       4
Charmeleon       3
                ..
Iron Valiant    15
Koraidon        16
Miraidon        16
Walking Wake    13
Iron Leaves     14
Name: Type, Length: 1010, dtype: int64

In [69]:
def count_of_a(s):
    return s.count("a")

pokemon.apply(count_of_a) # applies the count_of_a() function to each value in the Series, returning a new Series with the count of "a" in each value

Name
Bulbasaur       1
Ivysaur         0
Venusaur        1
Charmander      0
Charmeleon      0
               ..
Iron Valiant    1
Koraidon        1
Miraidon        1
Walking Wake    2
Iron Leaves     1
Name: Type, Length: 1010, dtype: int64

In [70]:
# The map() method is similar to apply(), but it is used for mapping values in a Series to new values based on a mapping dictionary or a function.

pokemon.map(len) # maps the len() function to each value in the Series, returning a new Series with the lengths of each value

Name
Bulbasaur       13
Ivysaur          4
Venusaur         5
Charmander       4
Charmeleon       3
                ..
Iron Valiant    15
Koraidon        16
Miraidon        16
Walking Wake    13
Iron Leaves     14
Name: Type, Length: 1010, dtype: int64

In [71]:
attack_powers = { "Grass": 10, "Fire": 20, "Water": 15, "Bug": 5, "Poison": 8 }
pokemon.map(attack_powers) # maps the attack_powers dictionary to each value in the Series, returning a new Series with the corresponding attack power for each type of Pokemon (NaN for

Name
Bulbasaur        NaN
Ivysaur         20.0
Venusaur        15.0
Charmander      20.0
Charmeleon       5.0
                ...
Iron Valiant     NaN
Koraidon         NaN
Miraidon         NaN
Walking Wake     NaN
Iron Leaves      NaN
Name: Type, Length: 1010, dtype: float64

In [72]:
attack_powers = pd.Series({ "Grass": 10, "Fire": 20, "Water": 15, "Bug": 5, "Poison": 8 })
pokemon.map(attack_powers) # maps the attack_powers Series to each value in the Series, returning a new Series with the corresponding attack power for each type of Pokemon (NaN for values not found in the attack_powers Series)

Name
Bulbasaur        NaN
Ivysaur         20.0
Venusaur        15.0
Charmander      20.0
Charmeleon       5.0
                ...
Iron Valiant     NaN
Koraidon         NaN
Miraidon         NaN
Walking Wake     NaN
Iron Leaves      NaN
Name: Type, Length: 1010, dtype: float64

In [73]:
s = pd.Series([4,8,6,5,3,7])
7 in s.values != 10 in s.values # checks if the value 7 is in the Series and if the value 10 is in the Series, returning True if both conditions are met and False otherwise

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
s = pd.Series([4,8,6,5,3,7])
s.mean()