## Working with Dash

### Overview
* Open Source User Interface Python library from Plotly for creating reactive web-app.
* Dash apps are web servers running Flask and communicating JSON packets over HTTP requests.
* Dash frontend renders components using React.js.
* Dash is declarative and reactive.
* It can be rendered in web browser and deploy to servers.
* Inherently cross-platform and mobile ready.

### Dash Components
* Core Components
    * import dash_core_components as dcc
* HTML Components
    * import dash_html_components as html

### Core Components
* Higher level components that are interactive and are generated with Javascript, HTML, and CSS via React.js library.
* Example: a slider, input area, check items, datepicker, etc.

### HTML Components
* has a components for every HTML tag.
* the dash_HTML_components library provides classes for all HTML tags.

### Flight Delay Time Statistics Dashboard
* we use the Skills Network Labs Cloud IDE environment for development.

### Dataset
1. Airline Reporting Carrier On-Time Performance dataset.
2. Information on approx 200 million domestic US flights.
3. Basic info about each flight: Time, date, departure & arrival airport, duration of flight delay, etc.

### Dashboard Flight Delays Analysis
* Monthly Average Carrier Delay
* Monthly Average Weather Delay
* Monthly Average National Air System Delay
* Monthly Average Security Delay
* Monthly Average Late Aircraft Delay

#### Goal
Create a dashboard that displays the percentage of flights running under specific distance group. Distance group is the distance intervals, every 250 miles, for flight segment. If the flight covers to 500 miles, it will be under distance group 2 (250 miles + 250 miles).

In [1]:
from dash import Dash, html, dcc
import plotly.express as px
import pandas as pd

In [2]:
# read the airline data into pandas dataframe
df_airline = pd.read_csv("data/airline_data.csv", dtype={'Div1Airport': str, 'Div1TailNum': str, 'Div2Airport': str, 'Div2TailNum': str})

# randomly sample 500 data points.
data = df_airline.sample(n=500, random_state=42)

data

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
5312,985989,2006,1,3,29,3,2006-03-29,OO,20304,OO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18357,1782939,1993,3,8,3,2,1993-08-03,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6428,84140,1989,3,7,3,1,1989-07-03,HP,19991,HP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15414,1839736,2008,4,10,10,5,2008-10-10,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10610,1622640,2010,1,2,19,5,2010-02-19,FL,20437,FL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18946,61420,2005,3,7,6,3,2005-07-06,WN,19393,WN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16291,458237,2019,2,6,1,6,2019-06-01,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21818,557936,1999,1,3,4,4,1999-03-04,HP,19991,HP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24116,1268298,2017,2,4,14,5,2017-04-14,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16705,1496740,2019,1,1,26,6,2019-01-26,AA,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# pie chart creation
fig = px.pie(data, values='Flights', names='DistanceGroup', title='Distance group proportion by flights')

In [4]:
# create a dash app
app = Dash(__name__)

# Get the layout of the application and adjust it.
# Create an outer division using html.Div and add title to the dashboard using html.H1 component
# Add description about the graph using HTML P (paragraph) component
# Finally, add graph component.
app.layout = html.Div(children=[html.H1("Airline On-Time Performance Dashboard", style={'textAlign':'center', 'color':"#967264", 'font-size':40}),
                                html.P('Proportion of distance group (250 mile distance)'),
                                dcc.Graph(figure=fig),
                                               
                    ])

# run the app
if __name__ == '__main__':
    app.run(jupyter_mode="inline") # "inline" "external" "jupyterlab"

## Make Dashboards Interactive

* a Callback function is a python function that is automatically called by Dash when any of its input properties changes.
* Callback function is decorated with @app.callback

### Exercise 1
Extract the average monthly arrival delay time and see how it changes over the year. The year range from 2010 to 2020.

In [5]:
# 1. import all the needed libraries
import pandas as pd
import plotly.graph_objects as go
import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

In [6]:
# 2. read and ready the dataset
# read the airline data into pandas dataframe
df_airline = pd.read_csv("data/airline_data.csv", dtype={'Div1Airport': str, 'Div1TailNum': str, 'Div2Airport': str, 'Div2TailNum': str})
df_airline.groupby('DestState')['Flights'].count().reset_index()

   DestState  Flights
0         AK      192
1         AL      163
2         AR      118
3         AZ      842
4         CA     3174
5         CO      970
6         CT      122
7         FL     1804
8         GA     1553
9         HI      289
10        IA       84
11        ID       72
12        IL     1766
13        IN      192
14        KS       44
15        KY      463
16        LA      265
17        MA      484
18        MD      421
19        ME       34
20        MI      768
21        MN      591
22        MO      730
23        MS       67
24        MT       79
25        NC      907
26        ND       53
27        NE      106
28        NH       34
29        NJ      539
30        NM      142
31        NV      704
32        NY     1233
33        OH      538
34        OK      203
35        OR      298
36        PA      834
37        PR       92
38        RI       71
39        SC      118
40        SD       34
41        TN      612
42        TT        3
43        TX     3023
44        UT      439
45        VA      882
46        VI       16
47        VT       23
48        WA      545
49        WI      210
50        WV       20
51        WY       27

In [7]:
# 3. create dash app and get the layout

# Create a dash application layout
app = dash.Dash(__name__)
# Get the layout of the application and adjust it.
# Create an outer division using html.Div and add title to the dashboard using html.H1 component
# Add a html.Div and core input text component
# Finally, add graph component.
app.layout = html.Div(children=
                      [ 
                        html.H1('Airline Performance Dashboard',style={'textAlign':'center', 'color':"#3A231A", 'font-size':40}),
                        html.Div(
                            ["Input Year: ", dcc.Input(id='input-year', value='2010', type='number', style={'width':'10%','height':'50px', 'font-size':35})], 
                            style={
                                'font-size':40,
                                'display':'flex', # puts all items on the same line
                                'alignItems':'center', # vertically align items to center
                                'justifyContent':'center', # horizontally center the whole group
                            }
                        ),
                        html.Br(),
                        html.Br(),
                        html.Div(dcc.Graph(id='line-plot')),
                      ],
                        style={
                            'backgroundColor':"#E4DBDB", 
                            'minHeight':'100vh', # Ensures the background covers the full screen height
                            'padding':'20px'
                        }
                     )

# add callback decorator
@app.callback( Output(component_id='line-plot', component_property='figure'),
               Input(component_id='input-year', component_property='value'))

# Add computation to callback function and return graph
def get_graph(entered_year):
    # Select 2019 data
    df =  df_airline[df_airline['Year']==int(entered_year)]
    
    # Group the data by Month and compute average over arrival delay time.
    line_data = df.groupby('Month')['ArrDelay'].mean().reset_index()
    fig = go.Figure(data=go.Scatter(x=line_data['Month'], y=line_data['ArrDelay'], mode='lines', marker=dict(color='green')))
    fig.update_layout(title='Month vs Average Flight Delay Time', xaxis_title='Month', yaxis_title='ArrDelay')
    return fig


# run the app
if __name__ == '__main__':
    app.run(jupyter_mode="inline") # "inline" "external" "jupyterlab"

### Exercise 2
Use a bar chart to extract the number of flights from a specific airline that goes to a destination.

In [8]:
# Create a dash application layout
app = dash.Dash(__name__)
# Get the layout of the application and adjust it.
# Create an outer division using html.Div and add title to the dashboard using html.H1 component
# Add a html.Div and core input text component
# Finally, add graph component.
app.layout = html.Div(children=
                      [ 
                        html.H1('Total number of flights to the destination state split by reporting airline',style={'textAlign':'center', 'color':"#3A231A", 'font-size':40}),
                        html.Div(
                            ["Input Year: ", dcc.Input(id='input-year', value='2010', type='number', style={'width':'10%','height':'50px', 'font-size':35})], 
                            style={
                                'font-size':40,
                                'display':'flex', # puts all items on the same line
                                'alignItems':'center', # vertically align items to center
                                'justifyContent':'center', # horizontally center the whole group
                            }
                        ),
                        html.Br(),
                        html.Br(),
                        html.Div(dcc.Graph(id='line-plot')),
                      ],
                        style={
                            'backgroundColor':"#E4DBDB", 
                            'minHeight':'100vh', # Ensures the background covers the full screen height
                            'padding':'20px'
                        }
                     )

# add callback decorator
@app.callback( Output(component_id='line-plot', component_property='figure'),
               Input(component_id='input-year', component_property='value'))

# Add computation to callback function and return graph
def get_graph(entered_year):
    # Select 2019 data
    df =  df_airline[df_airline['Year']==int(entered_year)]
    
    # Group the data by Month and compute average over arrival delay time.
    bar_data = df.groupby('DestState')['Flights'].count().reset_index()
    fig = px.bar(bar_data, x="DestState", y="Flights", title='Total number of flights to the destination state split by reporting airline') 
    return fig


# run the app
if __name__ == '__main__':
    app.run(jupyter_mode="inline") # "inline" "external" "jupyterlab"

## Flight Delay Time Statistics Dashboard

In [9]:
# Import required libraries
import pandas as pd
import dash
from dash import dcc
from dash import html
from dash.dependencies import Input, Output
import plotly.express as px

In [10]:
# Read the airline data into pandas dataframe
airline_data =  pd.read_csv('data/airline_data.csv', 
                            encoding = "ISO-8859-1",
                            dtype={'Div1Airport': str, 'Div1TailNum': str, 
                                   'Div2Airport': str, 'Div2TailNum': str})

In [11]:
""" Compute_info function description
This function takes in airline data and selected year as an input and performs computation for creating charts and plots.
Arguments:
    airline_data: Input airline data.
    entered_year: Input year for which computation needs to be performed.
Returns:
    Computed average dataframes for carrier delay, weather delay, NAS delay, security delay, and late aircraft delay.
"""
def compute_info(airline_data, entered_year):
    # Select data
    df =  airline_data[airline_data['Year']==int(entered_year)]
    # Compute delay averages
    avg_car = df.groupby(['Month','Reporting_Airline'])['CarrierDelay'].mean().reset_index()
    avg_weather = df.groupby(['Month','Reporting_Airline'])['WeatherDelay'].mean().reset_index()
    avg_NAS = df.groupby(['Month','Reporting_Airline'])['NASDelay'].mean().reset_index()
    avg_sec = df.groupby(['Month','Reporting_Airline'])['SecurityDelay'].mean().reset_index()
    avg_late = df.groupby(['Month','Reporting_Airline'])['LateAircraftDelay'].mean().reset_index()
    return avg_car, avg_weather, avg_NAS, avg_sec, avg_late

In [12]:
# Create a dash application
app = dash.Dash(__name__)

# Build dash app layout
app.layout = html.Div(children=[ 
        html.H1('Flight Delay Time Statistics', style={'textAlign':'center', 'color':"#3A231A", 'font-size':40}),
        html.Div(
            ["Input Year: ", dcc.Input(id='input-year', value='2010', type='number', style={'width':'10%','height':'50px', 'font-size':35})], 
            style={
                'font-size':40,
                'display':'flex', # puts all items on the same line
                'alignItems':'center', # vertically align items to center
                'justifyContent':'center', # horizontally center the whole group
            }
        ),
        
        html.Br(),
        html.Br(), 
        
        # Segment 1
        html.Div(
            [
                html.Div(dcc.Graph(id='carrier-plot')),
                html.Div(dcc.Graph(id='weather-plot'))
            ], style={'display': 'flex'}
        ),
        
        # Segment 2
        html.Div(
            [
                html.Div(dcc.Graph(id='nas-plot')),
                html.Div(dcc.Graph(id='security-plot'))
            ], style={'display': 'flex'}
        ),
        
        # Segment 3
        html.Div(dcc.Graph(id='late-plot'), style={'width':'65%'}),
    ],
    style={
        'backgroundColor':"#FFFFFF", 
        'minHeight':'100vh', # Ensures the background covers the full screen height
        'padding':'20px'
    }
)


"""Callback Function
Function that returns fugures using the provided input year.
Arguments:
    entered_year: Input year provided by the user.
Returns:
    List of figures computed using the provided helper function `compute_info`.
"""
# Callback decorator
@app.callback( [
               Output(component_id='carrier-plot', component_property='figure'),
               Output(component_id='weather-plot', component_property='figure'),
               Output(component_id='nas-plot', component_property='figure'),
               Output(component_id='security-plot', component_property='figure'),
               Output(component_id='late-plot', component_property='figure')
               ],
               Input(component_id='input-year', component_property='value'))
# Computation to callback function and return graph
def get_graph(entered_year):
    
    # Compute required information for creating graph from the data
    avg_car, avg_weather, avg_NAS, avg_sec, avg_late = compute_info(airline_data, entered_year)
            
    # Line plot for carrier delay
    carrier_fig = px.line(avg_car, x='Month', y='CarrierDelay', color='Reporting_Airline', title='Average carrrier delay time (minutes) by airline')
    # Line plot for weather delay
    weather_fig = px.line(avg_weather, x='Month', y='WeatherDelay', color='Reporting_Airline', title='Average weather delay time (minutes) by airline')
    # Line plot for nas delay
    nas_fig = px.line(avg_NAS, x='Month', y='NASDelay', color='Reporting_Airline', title='Average NAS delay time (minutes) by airline')
    # Line plot for security delay
    sec_fig = px.line(avg_sec, x='Month', y='SecurityDelay', color='Reporting_Airline', title='Average security delay time (minutes) by airline')
    # Line plot for late aircraft delay
    late_fig = px.line(avg_late, x='Month', y='LateAircraftDelay', color='Reporting_Airline', title='Average late aircraft delay time (minutes) by airline')
            
    return[carrier_fig, weather_fig, nas_fig, sec_fig, late_fig]


# Run the app
if __name__ == '__main__':
    app.run(jupyter_mode="inline") # "inline" "external" "jupyterlab"