## Options and Settings

In [1]:
import pandas as pd
import numpy as np

### Changing Options with Attributes
    * the pd.options module configures Pandas' settings.
    * the display module deals with the presentation of data.
    * the min_rows attribute sets the minimum number of displayed rows when max_rows is exceeded.
    * the max_columns attribute sets the maximum number of displayed columns. There is no min_columns attribute.
    * overwrite an attribute's value with an equal sign and the new value.

In [2]:
np.random.randint(0, 100) # generate a random number from 0 to 100

66

In [3]:
np.random.randint(0, 100, [60, 50]) # genrate a 2D random numbers between 0 to 100

array([[27, 76, 61, ..., 19, 10, 35],
       [60, 16, 99, ..., 12, 81,  0],
       [12, 10,  8, ..., 28,  9, 18],
       ...,
       [38, 90, 78, ..., 61,  4, 30],
       [ 1, 33, 16, ..., 36, 88, 26],
       [ 1, 61,  8, ..., 46, 88, 10]], shape=(60, 50))

In [4]:
df = pd.DataFrame(np.random.randint(0, 100, [60, 50]))
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,93,40,14,0,79,78,72,96,95,45,...,89,31,69,27,12,7,33,77,99,85
1,93,2,44,56,14,19,10,94,54,59,...,18,44,72,26,99,53,10,45,92,28
2,15,96,69,36,70,68,43,43,43,40,...,27,9,5,18,6,40,36,16,0,59
3,40,51,23,11,91,53,21,27,64,80,...,7,35,63,32,4,22,15,2,92,80
4,84,2,60,63,81,89,19,35,26,51,...,81,0,30,30,77,90,81,98,21,54
5,57,35,20,15,63,85,9,45,46,28,...,49,63,20,93,20,19,15,55,30,30
6,79,97,88,58,7,33,56,2,21,24,...,25,84,28,77,79,39,98,37,18,6
7,7,54,54,44,46,41,31,60,48,82,...,42,98,87,80,78,1,32,39,47,24
8,85,93,18,59,71,62,14,10,46,27,...,14,35,53,18,47,68,43,81,72,2
9,70,36,16,84,10,1,27,98,18,65,...,63,21,55,2,76,19,51,81,11,48
10,54,68,79,77,28,76,8,77,85,85,...,84,63,55,29,74,94,4,82,63,58
11,95,42,91,63,27,36,71,26,79,7,...,33,13,67,38,97,29,75,61,28,95
12,16,22,86,34,48,66,7,67,9,52,...,6,33,27,58,16,34,97,88,3,50
13,10,61,70,83,68,78,54,81,18,89,...,32,18,72,43,21,51,31,66,4,80
14,62,29,86,52,19,59,10,44,88,94,...,91,38,29,0,25,73,78,13,68,11
15,78,75,97,33,84,97,71,90,25,90,...,10,32,3,82,10,10,32,86,51,33
16,97,6,94,89,62,84,13,69,78,68,...,48,67,28,53,6,96,65,97,42,13
17,26,14,93,15,31,16,44,54,42,81,...,80,25,28,77,87,3,93,45,63,84
18,5,20,33,84,41,95,21,13,33,77,...,31,54,34,6,77,50,77,28,71,8
19,54,12,37,28,45,98,36,1,33,70,...,72,23,29,77,53,82,91,93,68,81
20,98,19,5,64,90,46,10,71,58,86,...,17,64,5,99,56,12,89,73,73,33
21,52,43,55,79,68,96,16,26,64,61,...,10,22,57,8,62,51,15,91,86,13
22,26,72,51,41,11,79,96,90,10,40,...,76,61,23,9,44,87,27,99,35,54
23,35,67,97,70,25,29,37,68,94,81,...,9,35,42,97,13,63,70,78,88,35
24,25,79,32,46,34,70,71,34,64,49,...,60,42,66,99,44,8,58,86,9,30
25,83,51,55,96,29,16,39,54,93,44,...,30,84,46,64,7,70,66,65,29,56
26,56,38,60,29,18,96,79,29,85,62,...,6,53,5,59,91,17,92,56,31,89
27,12,96,44,45,99,66,0,8,0,50,...,21,99,58,46,54,98,33,56,63,27
28,14,78,79,16,66,44,48,66,92,80,...,50,97,83,44,40,93,88,68,38,6
29,75,91,17,31,87,8,60,92,72,15,...,82,56,93,5,34,10,84,54,70,2
30,41,92,51,62,22,84,18,23,67,61,...,19,36,16,78,67,75,83,51,65,80
31,28,35,30,87,15,33,37,79,67,43,...,54,43,55,67,15,80,69,22,98,56
32,21,6,18,41,73,10,44,8,67,89,...,84,49,93,12,96,80,18,26,16,45
33,36,36,68,52,21,29,15,67,49,36,...,85,14,87,82,71,92,65,22,32,62
34,84,5,4,75,15,4,96,85,50,87,...,49,91,1,58,52,13,70,34,89,63
35,54,13,83,17,99,97,80,13,92,34,...,62,95,40,32,53,57,31,41,81,26
36,10,36,42,85,5,17,90,75,13,66,...,50,14,66,31,1,17,56,50,0,69
37,52,47,84,67,65,45,30,51,86,26,...,53,63,79,0,14,43,6,42,70,10
38,0,51,89,22,80,2,42,82,82,24,...,44,38,86,44,51,34,45,49,99,5
39,68,10,59,73,36,62,68,41,54,22,...,56,64,58,59,62,77,81,6,66,15
40,29,34,80,97,39,56,65,47,16,21,...,42,9,0,81,33,82,89,72,80,12
41,17,4,6,13,61,39,10,52,17,61,...,92,18,89,90,91,1,12,80,13,8
42,11,60,78,29,42,18,59,37,65,71,...,10,59,20,60,48,50,35,40,5,88
43,5,19,64,46,99,0,56,97,91,10,...,73,64,91,88,99,47,78,49,53,94
44,98,47,89,87,77,61,30,45,76,87,...,75,88,39,81,35,96,99,81,38,24
45,18,39,83,66,48,32,44,24,79,85,...,18,8,91,73,8,91,25,6,16,77
46,91,68,51,73,4,99,59,87,69,57,...,62,23,4,79,74,65,19,35,10,40
47,78,67,61,5,7,96,68,82,99,42,...,75,18,52,97,47,25,94,83,93,38
48,96,95,14,99,59,12,74,67,74,9,...,33,60,97,63,20,89,32,85,8,95
49,34,37,85,91,65,66,83,3,99,20,...,4,75,45,83,2,25,55,86,47,53
50,21,89,38,10,72,35,30,38,15,12,...,84,29,26,82,41,25,97,18,43,22
51,0,80,0,44,44,69,42,98,28,33,...,58,47,13,60,42,5,10,57,88,67
52,63,76,11,41,64,74,28,53,22,57,...,37,10,15,85,47,97,73,4,98,15
53,60,82,38,59,54,15,91,39,51,54,...,45,71,78,57,56,4,16,30,78,19
54,85,87,85,57,99,64,76,27,10,80,...,7,37,34,4,75,27,60,66,5,76
55,15,58,22,19,55,21,61,58,83,73,...,26,57,86,15,16,8,21,58,11,31
56,81,82,22,89,77,49,88,53,73,84,...,37,7,38,1,44,78,73,36,27,83
57,93,12,79,95,86,28,90,10,33,1,...,25,76,17,33,51,50,75,63,0,28
58,97,8,79,57,95,93,70,74,96,21,...,10,28,36,79,67,86,5,61,57,32
59,24,0,64,99,90,13,54,92,16,85,...,85,51,82,23,37,85,70,27,43,79

In [5]:
# Note the above display all the rows, but left out some of the columns, but we can customise this behaviour.
pd.options.display.min_rows

10

In [6]:
pd.options.display.max_rows

60

In [7]:
pd.options.display.min_rows = 20
pd.options.display.max_rows = 50
df = pd.DataFrame(np.random.randint(0, 100, [61, 50]))
df

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,7,11,5,48,9,77,99,53,13,56,...,35,20,34,64,78,41,23,7,4,49
1,48,42,23,55,87,8,9,28,69,44,...,75,26,66,32,16,4,86,12,49,73
2,63,33,32,12,20,3,27,83,36,16,...,19,94,12,20,82,26,89,38,23,65
3,86,24,52,65,40,91,51,62,89,97,...,79,30,20,18,63,87,97,69,92,47
4,31,90,63,72,34,1,24,79,51,28,...,46,55,83,8,6,40,19,2,0,3
5,0,61,44,45,7,30,51,40,52,80,...,11,17,16,38,28,50,18,88,41,68
6,93,45,25,74,8,76,63,50,43,12,...,87,84,41,3,23,55,11,22,95,15
7,93,69,87,44,40,60,36,94,34,97,...,42,49,56,20,1,46,43,37,95,62
8,52,74,52,5,56,8,99,46,59,80,...,6,24,12,9,31,81,56,32,42,93
9,30,72,34,15,41,84,87,93,20,1,...,87,78,3,90,65,69,51,27,74,79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,76,98,61,17,48,68,37,15,73,66,...,89,62,93,3,48,35,90,24,28,60
52,89,75,56,28,52,97,54,69,16,86,...,89,11,96,95,37,9,79,19,30,75
53,10,97,63,50,77,61,95,33,56,78,...,34,32,59,96,56,48,10,60,72,11
54,3,31,15,16,90,78,15,90,15,91,...,88,47,31,94,98,94,45,88,55,16
55,83,49,74,72,51,38,30,45,9,59,...,64,46,43,81,66,15,91,47,33,47
56,40,42,92,22,13,27,93,16,77,88,...,45,18,79,5,15,10,77,11,22,97
57,25,37,15,65,49,6,82,26,92,11,...,94,33,62,57,65,2,71,57,61,46
58,78,20,1,61,84,37,33,66,11,46,...,86,45,12,51,22,15,0,48,52,16
59,48,80,94,42,90,75,94,79,62,12,...,57,74,40,37,54,53,59,51,88,73
60,91,42,28,28,38,33,3,77,62,26,...,83,98,49,82,35,28,86,42,44,14

In [8]:
pd.options.display.max_columns = 50
df = pd.DataFrame(np.random.randint(0, 100, [61, 50]))
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,0,27,76,19,76,52,75,78,62,13,59,17,49,57,33,40,9,34,15,29,89,45,40,88,4,40,53,17,65,59,56,68,41,46,59,34,59,80,86,56,78,22,17,69,99,80,3,32,59,13
1,56,94,59,1,22,32,49,92,18,61,20,38,54,22,78,94,89,64,51,83,94,11,51,11,28,57,33,71,69,53,18,15,99,40,26,26,41,87,90,34,34,71,54,4,54,45,7,52,96,53
2,90,5,11,76,91,97,93,86,24,11,39,82,49,32,92,21,66,11,44,80,47,6,74,36,1,46,5,84,21,0,53,32,62,38,56,23,50,57,49,32,51,89,9,2,4,78,31,59,27,77
3,50,39,7,7,89,53,75,50,28,88,81,13,36,83,6,10,27,26,56,64,46,66,95,15,58,0,6,21,65,1,24,97,22,25,24,87,9,87,56,39,52,40,33,35,80,0,66,17,12,68
4,9,93,29,32,59,72,6,66,45,44,69,35,4,3,32,92,43,95,51,85,70,24,42,95,33,74,20,92,27,50,70,59,74,39,21,96,83,1,87,68,36,55,91,17,14,36,49,86,77,44
5,69,79,15,54,53,28,10,70,8,86,52,55,17,25,48,68,44,46,95,16,21,75,17,80,40,40,66,75,47,50,79,16,65,51,28,63,51,3,4,67,58,72,23,48,57,6,84,66,80,70
6,91,35,62,58,25,1,6,96,1,29,71,96,33,78,17,84,28,40,86,28,55,64,83,77,97,60,37,27,94,89,34,53,80,6,66,44,83,43,74,58,65,10,46,14,23,75,36,63,49,75
7,30,80,41,13,87,92,28,90,6,62,27,80,89,24,30,70,19,32,84,99,50,78,34,2,39,16,55,66,56,19,97,52,70,44,53,5,65,67,98,22,18,70,47,11,4,36,82,35,33,43
8,69,16,78,25,48,54,77,37,80,19,9,88,75,88,96,29,21,46,10,64,29,61,44,8,48,33,87,57,95,14,92,76,18,95,22,39,47,51,93,7,63,32,27,3,22,23,41,44,26,10
9,93,86,24,75,77,15,11,53,29,89,57,10,98,82,38,26,78,62,63,29,13,80,5,73,93,31,51,93,38,32,18,95,10,88,59,26,66,31,61,14,67,95,47,28,91,77,49,82,79,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,89,69,13,73,32,49,54,47,64,43,94,22,90,99,70,46,68,2,2,84,8,8,16,55,91,46,22,83,24,46,93,99,14,18,99,45,93,51,49,95,36,20,55,91,22,27,37,65,21,65
52,36,78,65,55,20,87,2,15,5,51,92,37,55,87,87,32,26,30,27,2,64,47,39,15,68,61,7,92,55,73,50,12,69,41,17,70,22,69,70,3,60,9,38,64,94,20,8,82,0,84
53,17,94,92,11,69,93,69,12,94,69,8,69,40,65,64,81,78,29,9,60,87,61,22,4,25,73,37,32,54,55,70,70,13,18,55,46,79,74,14,50,18,65,2,82,45,38,55,38,63,9
54,14,17,4,60,48,23,9,63,49,98,81,75,5,8,28,31,51,5,21,62,90,69,82,81,63,21,60,96,45,66,70,14,71,99,67,67,56,51,98,45,48,20,76,21,96,29,61,42,78,99
55,82,1,7,84,89,89,84,75,7,16,89,53,7,7,15,5,47,98,5,8,53,8,61,38,40,25,24,4,82,48,33,53,77,71,37,74,92,89,69,67,44,35,75,14,99,11,11,58,55,44
56,11,6,83,56,72,12,63,31,4,92,86,48,15,60,45,64,98,44,7,83,68,43,98,40,7,16,19,15,74,13,9,47,22,40,56,38,7,55,27,36,58,20,7,54,14,24,47,46,11,18
57,13,89,78,11,67,48,40,5,3,15,34,80,86,92,25,32,46,70,33,19,37,1,94,94,60,18,23,36,55,20,48,33,45,61,50,22,29,22,83,13,64,44,55,56,62,89,8,39,7,58
58,26,11,21,24,90,9,57,99,74,70,38,75,90,88,28,40,24,96,88,60,39,30,89,91,48,33,26,51,50,40,79,56,51,17,99,26,8,87,51,8,84,70,48,42,39,4,94,95,84,93
59,23,70,25,81,14,93,39,20,72,86,81,74,17,37,89,90,70,81,32,84,12,11,54,33,52,24,5,19,61,60,23,5,28,45,25,1,80,48,70,97,24,40,77,0,53,35,65,12,14,55
60,26,96,99,14,77,56,52,19,15,8,78,69,49,58,29,82,58,11,57,94,38,6,85,5,69,46,2,16,64,42,3,15,32,64,92,65,63,22,33,60,40,15,29,35,88,24,23,16,79,94

In [9]:
pd.options.display.max_columns = None  # no limit
df = pd.DataFrame(np.random.randint(0, 100, [61, 50]))
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,2,66,76,21,69,50,35,20,46,93,99,62,34,63,69,41,56,17,47,87,72,75,83,89,95,5,8,90,9,21,89,85,2,13,30,11,61,74,53,38,27,40,42,91,71,44,10,54,75,14
1,5,28,71,7,35,46,1,41,31,56,9,25,7,39,98,20,23,70,30,41,6,33,22,15,47,80,45,94,63,45,13,42,7,44,70,43,20,54,10,88,62,53,46,53,81,39,34,8,94,28
2,44,82,93,63,99,4,15,15,82,93,96,64,74,36,3,18,96,34,14,82,42,26,75,20,20,11,80,99,19,47,57,95,97,35,51,55,50,77,18,75,15,5,30,54,64,33,52,40,59,17
3,71,34,60,82,19,0,30,42,89,44,25,9,91,52,4,40,40,7,90,82,40,67,92,7,58,19,42,8,83,48,81,14,49,50,29,21,23,88,26,44,19,44,26,85,53,67,7,74,81,26
4,80,40,70,79,24,88,97,40,89,16,85,92,56,23,90,19,38,68,40,97,67,76,85,24,17,94,10,83,15,32,73,11,17,85,11,24,21,77,10,88,32,34,97,25,71,88,24,6,18,24
5,7,33,15,27,83,51,39,38,62,93,64,5,38,64,23,29,18,89,24,5,18,87,99,51,0,70,28,4,54,63,79,50,54,26,79,86,99,87,3,93,72,38,49,57,51,13,68,97,65,92
6,78,46,95,67,16,33,73,5,10,8,10,82,27,71,56,63,0,32,74,73,43,51,89,33,51,3,18,14,61,78,95,57,22,7,37,70,26,8,62,10,30,80,10,48,2,49,84,77,83,32
7,19,66,12,76,36,21,7,92,1,20,48,64,40,61,41,22,56,24,23,28,62,37,39,55,15,39,40,37,97,66,32,88,76,33,62,32,96,40,82,81,73,63,20,57,33,13,54,49,73,5
8,8,85,30,46,33,14,67,22,5,75,43,30,26,92,40,14,95,61,87,70,13,50,60,15,59,37,62,57,94,13,42,11,59,13,61,10,24,45,77,46,42,46,15,38,56,13,2,4,88,94
9,88,33,79,43,26,24,0,42,13,50,66,13,24,99,43,62,5,18,66,41,41,77,98,48,67,48,26,92,2,58,49,42,94,92,51,15,69,98,10,99,11,94,28,22,69,55,42,15,64,60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,53,27,41,35,56,94,98,65,32,84,42,40,49,53,40,46,40,69,80,6,29,72,10,95,70,21,21,47,9,71,4,5,4,3,19,66,81,73,68,62,25,77,41,59,98,77,46,87,67,35
52,0,77,49,10,78,9,2,3,56,63,21,98,10,72,4,96,29,93,13,49,61,98,89,87,16,57,13,91,39,6,57,86,39,84,66,26,39,25,9,82,17,39,82,4,92,99,75,36,34,83
53,59,0,58,65,82,60,61,80,11,33,67,63,58,53,13,51,46,34,91,58,10,10,29,29,10,90,53,55,87,39,73,10,62,39,39,48,15,63,26,59,48,25,51,29,35,70,9,59,49,40
54,71,35,21,66,82,84,23,51,33,7,78,30,22,27,44,45,76,88,31,25,64,97,15,23,9,50,74,91,9,44,14,39,4,44,95,0,5,11,32,29,4,28,88,42,95,90,6,23,97,68
55,46,62,75,81,85,49,33,68,17,64,59,29,67,15,80,62,70,84,32,69,93,68,23,9,93,7,67,73,48,56,13,21,69,98,96,35,58,34,6,64,40,71,74,37,33,72,86,55,34,22
56,71,92,50,25,13,89,87,29,43,93,50,21,62,96,41,55,40,87,39,94,60,72,82,39,30,36,37,11,84,46,14,3,4,16,23,35,79,98,74,4,67,80,76,72,83,98,46,8,38,18
57,98,99,68,3,66,93,83,78,63,33,67,63,65,8,78,87,7,10,46,6,46,82,25,8,85,89,25,90,6,50,22,25,56,86,13,74,10,66,92,1,77,73,24,90,37,25,31,57,0,60
58,41,86,49,53,81,37,85,78,81,81,48,2,16,83,98,66,89,42,88,55,59,80,73,46,81,4,90,96,91,87,84,36,67,52,44,13,56,8,8,95,78,98,35,35,50,60,24,36,56,28
59,37,94,29,78,65,39,25,1,48,13,75,95,14,12,19,50,92,30,17,76,15,60,85,14,96,64,10,20,36,28,61,32,59,26,97,62,82,16,90,80,71,73,19,98,75,35,16,92,54,37
60,93,57,38,20,5,87,12,17,48,91,79,79,91,51,53,37,89,73,50,35,11,23,47,88,67,6,11,84,77,85,74,37,58,80,78,53,33,28,0,32,34,77,86,86,81,29,46,46,5,72

In [10]:
pd.options.display.max_columns # reset
df = pd.DataFrame(np.random.randint(0, 100, [61, 50]))
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,38,52,22,94,42,21,14,85,37,17,83,38,19,27,81,72,44,90,83,60,63,77,81,35,2,14,71,82,62,99,74,75,7,64,17,48,39,0,31,92,84,23,84,74,39,46,63,57,7,65
1,87,61,52,28,82,64,74,75,78,67,43,85,64,95,88,3,65,70,31,82,19,90,20,19,89,20,71,4,57,3,41,18,52,43,22,64,89,71,30,2,43,5,21,19,50,76,24,48,90,68
2,9,7,79,88,75,1,98,95,25,73,60,64,31,13,81,68,96,91,1,62,71,80,96,9,11,31,23,78,9,47,3,92,15,76,13,25,4,36,60,19,62,57,77,98,9,64,95,63,6,31
3,30,50,66,12,20,14,88,4,61,29,3,72,5,71,53,51,47,80,36,79,56,34,16,82,49,84,49,48,62,4,44,27,19,57,88,95,98,84,23,33,71,15,78,70,64,44,14,23,85,37
4,99,35,37,79,36,91,70,40,15,92,30,81,95,26,70,8,65,47,80,54,95,48,47,34,21,42,82,58,89,84,66,30,27,4,50,41,60,3,61,37,58,61,14,93,2,5,45,16,21,10
5,21,39,59,89,33,22,70,4,22,47,33,34,82,39,71,50,84,0,64,45,57,16,97,44,22,70,74,24,31,31,55,93,0,1,82,29,90,21,5,13,46,80,40,65,42,35,34,5,89,77
6,90,77,79,88,30,16,13,15,44,30,88,0,78,19,89,41,31,4,65,78,27,71,11,46,17,39,48,52,10,56,81,76,94,50,41,26,6,23,88,88,52,39,15,24,8,31,95,79,76,72
7,50,47,23,46,57,87,36,97,31,70,85,74,63,60,22,39,22,52,19,95,76,82,15,52,34,93,11,37,70,89,52,3,33,80,71,84,31,23,4,17,38,80,37,31,2,5,35,87,47,76
8,9,61,68,5,13,76,69,43,30,13,14,2,49,30,35,83,3,77,68,82,60,87,23,74,24,36,55,36,43,0,48,60,58,56,69,9,42,8,9,0,32,16,43,20,23,44,60,18,96,39
9,6,56,1,80,55,79,87,98,96,4,41,87,30,94,84,94,59,49,73,96,88,9,90,97,78,23,49,70,24,82,36,78,8,70,70,23,53,18,30,59,63,83,95,4,67,6,29,47,78,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,22,73,0,55,79,16,80,41,99,11,89,53,49,1,58,2,2,86,66,59,41,71,43,80,72,60,51,88,82,5,45,95,35,52,35,63,72,7,15,83,71,95,53,5,33,90,75,37,50,46
52,23,21,62,4,55,8,68,69,39,15,46,4,59,15,30,29,5,59,50,72,82,95,67,73,58,48,64,84,87,25,70,11,76,80,34,82,98,77,39,82,43,23,0,97,92,11,35,85,68,91
53,13,22,3,81,10,34,74,26,65,25,44,36,74,12,51,17,41,73,38,40,44,17,34,75,1,48,91,60,65,26,2,38,65,36,88,15,27,44,17,18,95,59,81,64,89,12,13,75,17,34
54,16,3,34,37,6,32,10,20,66,31,54,76,85,51,36,66,28,11,12,58,21,53,31,45,61,14,0,83,19,85,79,65,13,47,84,82,45,26,39,8,15,15,68,70,76,16,97,83,60,58
55,94,11,7,58,27,23,48,20,88,58,65,56,44,45,5,96,44,34,7,98,49,20,52,25,46,32,92,17,79,87,77,43,31,20,37,64,27,95,51,87,59,36,27,70,32,95,40,66,10,84
56,70,75,47,6,8,15,60,26,20,98,7,98,37,85,17,65,35,30,71,70,19,11,28,20,27,89,3,65,63,3,26,40,84,65,94,60,55,60,69,99,43,75,50,29,69,25,97,88,37,88
57,80,82,94,54,44,57,28,12,54,75,71,58,17,37,71,42,13,34,30,66,10,34,57,93,29,0,32,64,36,72,95,88,85,4,87,19,18,75,91,71,82,63,88,8,32,1,70,74,35,4
58,7,95,58,44,15,68,85,51,40,59,41,0,13,16,22,60,91,79,84,18,43,25,61,15,85,23,74,31,99,89,30,2,27,40,19,44,95,10,25,59,42,96,54,94,48,51,59,42,70,45
59,5,1,53,35,13,77,35,92,46,27,68,96,55,27,7,47,90,94,24,75,58,94,1,69,65,46,99,70,29,56,27,46,73,81,64,14,11,86,6,3,31,93,65,86,50,12,21,19,53,53
60,58,41,76,1,1,49,98,73,77,40,40,36,37,61,23,5,88,26,45,30,16,73,52,56,20,98,58,59,3,38,73,5,95,36,7,2,40,95,62,2,76,97,44,7,13,66,2,80,99,47

### Changing Options with Functions
    * the pd.get_option function retrieves the current value for a pandas setting.
    * the pd.set_option function sets a new value for a pandas setting.
    * the pd.describe_option function provides documentation for a pandas setting.
    * the pd.reset_option function returns a pandas setting back to its default value.

In [11]:
pd.get_option("display.min_row")

20

In [12]:
pd.get_option("display.max_row")

50

In [13]:
pd.get_option("display.max_columns")

In [14]:
pd.set_option("display.max_row", 16)

In [15]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,38,52,22,94,42,21,14,85,37,17,83,38,19,27,81,72,44,90,83,60,63,77,81,35,2,14,71,82,62,99,74,75,7,64,17,48,39,0,31,92,84,23,84,74,39,46,63,57,7,65
1,87,61,52,28,82,64,74,75,78,67,43,85,64,95,88,3,65,70,31,82,19,90,20,19,89,20,71,4,57,3,41,18,52,43,22,64,89,71,30,2,43,5,21,19,50,76,24,48,90,68
2,9,7,79,88,75,1,98,95,25,73,60,64,31,13,81,68,96,91,1,62,71,80,96,9,11,31,23,78,9,47,3,92,15,76,13,25,4,36,60,19,62,57,77,98,9,64,95,63,6,31
3,30,50,66,12,20,14,88,4,61,29,3,72,5,71,53,51,47,80,36,79,56,34,16,82,49,84,49,48,62,4,44,27,19,57,88,95,98,84,23,33,71,15,78,70,64,44,14,23,85,37
4,99,35,37,79,36,91,70,40,15,92,30,81,95,26,70,8,65,47,80,54,95,48,47,34,21,42,82,58,89,84,66,30,27,4,50,41,60,3,61,37,58,61,14,93,2,5,45,16,21,10
5,21,39,59,89,33,22,70,4,22,47,33,34,82,39,71,50,84,0,64,45,57,16,97,44,22,70,74,24,31,31,55,93,0,1,82,29,90,21,5,13,46,80,40,65,42,35,34,5,89,77
6,90,77,79,88,30,16,13,15,44,30,88,0,78,19,89,41,31,4,65,78,27,71,11,46,17,39,48,52,10,56,81,76,94,50,41,26,6,23,88,88,52,39,15,24,8,31,95,79,76,72
7,50,47,23,46,57,87,36,97,31,70,85,74,63,60,22,39,22,52,19,95,76,82,15,52,34,93,11,37,70,89,52,3,33,80,71,84,31,23,4,17,38,80,37,31,2,5,35,87,47,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,13,22,3,81,10,34,74,26,65,25,44,36,74,12,51,17,41,73,38,40,44,17,34,75,1,48,91,60,65,26,2,38,65,36,88,15,27,44,17,18,95,59,81,64,89,12,13,75,17,34
54,16,3,34,37,6,32,10,20,66,31,54,76,85,51,36,66,28,11,12,58,21,53,31,45,61,14,0,83,19,85,79,65,13,47,84,82,45,26,39,8,15,15,68,70,76,16,97,83,60,58
55,94,11,7,58,27,23,48,20,88,58,65,56,44,45,5,96,44,34,7,98,49,20,52,25,46,32,92,17,79,87,77,43,31,20,37,64,27,95,51,87,59,36,27,70,32,95,40,66,10,84
56,70,75,47,6,8,15,60,26,20,98,7,98,37,85,17,65,35,30,71,70,19,11,28,20,27,89,3,65,63,3,26,40,84,65,94,60,55,60,69,99,43,75,50,29,69,25,97,88,37,88
57,80,82,94,54,44,57,28,12,54,75,71,58,17,37,71,42,13,34,30,66,10,34,57,93,29,0,32,64,36,72,95,88,85,4,87,19,18,75,91,71,82,63,88,8,32,1,70,74,35,4
58,7,95,58,44,15,68,85,51,40,59,41,0,13,16,22,60,91,79,84,18,43,25,61,15,85,23,74,31,99,89,30,2,27,40,19,44,95,10,25,59,42,96,54,94,48,51,59,42,70,45
59,5,1,53,35,13,77,35,92,46,27,68,96,55,27,7,47,90,94,24,75,58,94,1,69,65,46,99,70,29,56,27,46,73,81,64,14,11,86,6,3,31,93,65,86,50,12,21,19,53,53
60,58,41,76,1,1,49,98,73,77,40,40,36,37,61,23,5,88,26,45,30,16,73,52,56,20,98,58,59,3,38,73,5,95,36,7,2,40,95,62,2,76,97,44,7,13,66,2,80,99,47

In [16]:
pd.describe_option("display.max_rows")

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view.

    'None' value means unlimited. Beware that printing a large number of rows
    could cause your rendering environment (the browser, etc.) to crash.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 16]

In [17]:
pd.reset_option("display.max_rows")

In [18]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49
0,38,52,22,94,42,21,14,85,37,17,83,38,19,27,81,72,44,90,83,60,63,77,81,35,2,14,71,82,62,99,74,75,7,64,17,48,39,0,31,92,84,23,84,74,39,46,63,57,7,65
1,87,61,52,28,82,64,74,75,78,67,43,85,64,95,88,3,65,70,31,82,19,90,20,19,89,20,71,4,57,3,41,18,52,43,22,64,89,71,30,2,43,5,21,19,50,76,24,48,90,68
2,9,7,79,88,75,1,98,95,25,73,60,64,31,13,81,68,96,91,1,62,71,80,96,9,11,31,23,78,9,47,3,92,15,76,13,25,4,36,60,19,62,57,77,98,9,64,95,63,6,31
3,30,50,66,12,20,14,88,4,61,29,3,72,5,71,53,51,47,80,36,79,56,34,16,82,49,84,49,48,62,4,44,27,19,57,88,95,98,84,23,33,71,15,78,70,64,44,14,23,85,37
4,99,35,37,79,36,91,70,40,15,92,30,81,95,26,70,8,65,47,80,54,95,48,47,34,21,42,82,58,89,84,66,30,27,4,50,41,60,3,61,37,58,61,14,93,2,5,45,16,21,10
5,21,39,59,89,33,22,70,4,22,47,33,34,82,39,71,50,84,0,64,45,57,16,97,44,22,70,74,24,31,31,55,93,0,1,82,29,90,21,5,13,46,80,40,65,42,35,34,5,89,77
6,90,77,79,88,30,16,13,15,44,30,88,0,78,19,89,41,31,4,65,78,27,71,11,46,17,39,48,52,10,56,81,76,94,50,41,26,6,23,88,88,52,39,15,24,8,31,95,79,76,72
7,50,47,23,46,57,87,36,97,31,70,85,74,63,60,22,39,22,52,19,95,76,82,15,52,34,93,11,37,70,89,52,3,33,80,71,84,31,23,4,17,38,80,37,31,2,5,35,87,47,76
8,9,61,68,5,13,76,69,43,30,13,14,2,49,30,35,83,3,77,68,82,60,87,23,74,24,36,55,36,43,0,48,60,58,56,69,9,42,8,9,0,32,16,43,20,23,44,60,18,96,39
9,6,56,1,80,55,79,87,98,96,4,41,87,30,94,84,94,59,49,73,96,88,9,90,97,78,23,49,70,24,82,36,78,8,70,70,23,53,18,30,59,63,83,95,4,67,6,29,47,78,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,22,73,0,55,79,16,80,41,99,11,89,53,49,1,58,2,2,86,66,59,41,71,43,80,72,60,51,88,82,5,45,95,35,52,35,63,72,7,15,83,71,95,53,5,33,90,75,37,50,46
52,23,21,62,4,55,8,68,69,39,15,46,4,59,15,30,29,5,59,50,72,82,95,67,73,58,48,64,84,87,25,70,11,76,80,34,82,98,77,39,82,43,23,0,97,92,11,35,85,68,91
53,13,22,3,81,10,34,74,26,65,25,44,36,74,12,51,17,41,73,38,40,44,17,34,75,1,48,91,60,65,26,2,38,65,36,88,15,27,44,17,18,95,59,81,64,89,12,13,75,17,34
54,16,3,34,37,6,32,10,20,66,31,54,76,85,51,36,66,28,11,12,58,21,53,31,45,61,14,0,83,19,85,79,65,13,47,84,82,45,26,39,8,15,15,68,70,76,16,97,83,60,58
55,94,11,7,58,27,23,48,20,88,58,65,56,44,45,5,96,44,34,7,98,49,20,52,25,46,32,92,17,79,87,77,43,31,20,37,64,27,95,51,87,59,36,27,70,32,95,40,66,10,84
56,70,75,47,6,8,15,60,26,20,98,7,98,37,85,17,65,35,30,71,70,19,11,28,20,27,89,3,65,63,3,26,40,84,65,94,60,55,60,69,99,43,75,50,29,69,25,97,88,37,88
57,80,82,94,54,44,57,28,12,54,75,71,58,17,37,71,42,13,34,30,66,10,34,57,93,29,0,32,64,36,72,95,88,85,4,87,19,18,75,91,71,82,63,88,8,32,1,70,74,35,4
58,7,95,58,44,15,68,85,51,40,59,41,0,13,16,22,60,91,79,84,18,43,25,61,15,85,23,74,31,99,89,30,2,27,40,19,44,95,10,25,59,42,96,54,94,48,51,59,42,70,45
59,5,1,53,35,13,77,35,92,46,27,68,96,55,27,7,47,90,94,24,75,58,94,1,69,65,46,99,70,29,56,27,46,73,81,64,14,11,86,6,3,31,93,65,86,50,12,21,19,53,53
60,58,41,76,1,1,49,98,73,77,40,40,36,37,61,23,5,88,26,45,30,16,73,52,56,20,98,58,59,3,38,73,5,95,36,7,2,40,95,62,2,76,97,44,7,13,66,2,80,99,47

### The precision Option
    * the display.precision option sets the number of digits that appears after a decimal point in a floating-point number.
    * the default value is 6.

In [19]:
df = pd.DataFrame(np.random.randn(5, 5))
df

          0         1         2         3         4
0  1.093023 -0.567434 -1.985587 -0.107584  1.358598
1 -1.471181 -0.545445 -1.218742 -1.081449  0.200928
2  0.992375 -0.651106 -1.721584 -0.029612 -0.821630
3 -0.567798 -1.070001 -0.388569  0.650935  1.014977
4  0.165871 -1.335566 -0.567721 -0.226779 -1.137583

In [20]:
pd.options.display.precision

6

In [21]:
pd.get_option("display.precision")

6

In [22]:
pd.set_option("display.precision", 3)

In [23]:
df

       0      1      2      3      4
0  1.093 -0.567 -1.986 -0.108  1.359
1 -1.471 -0.545 -1.219 -1.081  0.201
2  0.992 -0.651 -1.722 -0.030 -0.822
3 -0.568 -1.070 -0.389  0.651  1.015
4  0.166 -1.336 -0.568 -0.227 -1.138

In [24]:
pd.reset_option("all")

/tmp/ipykernel_35445/3365680546.py:1: Pandas4Warning: 'future.no_silent_downcasting' is deprecated, please refrain from using it.
  pd.reset_option("all")
/tmp/ipykernel_35445/3365680546.py:1: Pandas4Warning: The 'mode.copy_on_write' option is deprecated. Copy-on-Write can no longer be disabled (it is always enabled with pandas >= 3.0), and setting the option has no impact. This option will be removed in pandas 4.0.
  pd.reset_option("all")